/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.Api;
using net.crossly.Model;
using net.crossly.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.Test.Model
{
    /// <summary>
    ///  Class for testing CreateEmbedKeyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateEmbedKeyResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateEmbedKeyResponse
        //private CreateEmbedKeyResponse instance;

        public CreateEmbedKeyResponseTests()
        {
            // TODO uncomment below to create an instance of CreateEmbedKeyResponse
            //instance = new CreateEmbedKeyResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateEmbedKeyResponse
        /// </summary>
        [Fact]
        public void CreateEmbedKeyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateEmbedKeyResponse
            //Assert.IsType<CreateEmbedKeyResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'AllowedOrigins'
        /// </summary>
        [Fact]
        public void AllowedOriginsTest()
        {
            // TODO unit test for the property 'AllowedOrigins'
        }

    }

}
