/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.Api;
using net.crossly.Model;
using net.crossly.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.Test.Model
{
    /// <summary>
    ///  Class for testing CreateCbxDisbursementRuleActiveResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCbxDisbursementRuleActiveResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateCbxDisbursementRuleActiveResponse
        //private CreateCbxDisbursementRuleActiveResponse instance;

        public CreateCbxDisbursementRuleActiveResponseTests()
        {
            // TODO uncomment below to create an instance of CreateCbxDisbursementRuleActiveResponse
            //instance = new CreateCbxDisbursementRuleActiveResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateCbxDisbursementRuleActiveResponse
        /// </summary>
        [Fact]
        public void CreateCbxDisbursementRuleActiveResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateCbxDisbursementRuleActiveResponse
            //Assert.IsType<CreateCbxDisbursementRuleActiveResponse>(instance);
        }


        /// <summary>
        /// Test the property 'RuleId'
        /// </summary>
        [Fact]
        public void RuleIdTest()
        {
            // TODO unit test for the property 'RuleId'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

    }

}
