/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.Api;
using net.crossly.Model;
using net.crossly.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.Test.Model
{
    /// <summary>
    ///  Class for testing CreateInboxCannedResponsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateInboxCannedResponsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateInboxCannedResponsResponse
        //private CreateInboxCannedResponsResponse instance;

        public CreateInboxCannedResponsResponseTests()
        {
            // TODO uncomment below to create an instance of CreateInboxCannedResponsResponse
            //instance = new CreateInboxCannedResponsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateInboxCannedResponsResponse
        /// </summary>
        [Fact]
        public void CreateInboxCannedResponsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateInboxCannedResponsResponse
            //Assert.IsType<CreateInboxCannedResponsResponse>(instance);
        }


        /// <summary>
        /// Test the property 'CannedResponse'
        /// </summary>
        [Fact]
        public void CannedResponseTest()
        {
            // TODO unit test for the property 'CannedResponse'
        }

    }

}
