/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.Api;
using net.crossly.Model;
using net.crossly.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.Test.Model
{
    /// <summary>
    ///  Class for testing GetAnalyticDashboardResponseRevenueByDay
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAnalyticDashboardResponseRevenueByDayTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAnalyticDashboardResponseRevenueByDay
        //private GetAnalyticDashboardResponseRevenueByDay instance;

        public GetAnalyticDashboardResponseRevenueByDayTests()
        {
            // TODO uncomment below to create an instance of GetAnalyticDashboardResponseRevenueByDay
            //instance = new GetAnalyticDashboardResponseRevenueByDay();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAnalyticDashboardResponseRevenueByDay
        /// </summary>
        [Fact]
        public void GetAnalyticDashboardResponseRevenueByDayInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAnalyticDashboardResponseRevenueByDay
            //Assert.IsType<GetAnalyticDashboardResponseRevenueByDay>(instance);
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Revenue'
        /// </summary>
        [Fact]
        public void RevenueTest()
        {
            // TODO unit test for the property 'Revenue'
        }
        /// <summary>
        /// Test the property 'Profit'
        /// </summary>
        [Fact]
        public void ProfitTest()
        {
            // TODO unit test for the property 'Profit'
        }
        /// <summary>
        /// Test the property 'Listings'
        /// </summary>
        [Fact]
        public void ListingsTest()
        {
            // TODO unit test for the property 'Listings'
        }

    }

}
