/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.Api;
using net.crossly.Model;
using net.crossly.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.Test.Model
{
    /// <summary>
    ///  Class for testing GetBuyerCatalogListingAvailabilityResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetBuyerCatalogListingAvailabilityResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetBuyerCatalogListingAvailabilityResponse
        //private GetBuyerCatalogListingAvailabilityResponse instance;

        public GetBuyerCatalogListingAvailabilityResponseTests()
        {
            // TODO uncomment below to create an instance of GetBuyerCatalogListingAvailabilityResponse
            //instance = new GetBuyerCatalogListingAvailabilityResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetBuyerCatalogListingAvailabilityResponse
        /// </summary>
        [Fact]
        public void GetBuyerCatalogListingAvailabilityResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetBuyerCatalogListingAvailabilityResponse
            //Assert.IsType<GetBuyerCatalogListingAvailabilityResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Fact]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }
        /// <summary>
        /// Test the property 'Available'
        /// </summary>
        [Fact]
        public void AvailableTest()
        {
            // TODO unit test for the property 'Available'
        }
        /// <summary>
        /// Test the property 'QuantityAvailable'
        /// </summary>
        [Fact]
        public void QuantityAvailableTest()
        {
            // TODO unit test for the property 'QuantityAvailable'
        }
        /// <summary>
        /// Test the property 'PriceCents'
        /// </summary>
        [Fact]
        public void PriceCentsTest()
        {
            // TODO unit test for the property 'PriceCents'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
