/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.Api;
using net.crossly.Model;
using net.crossly.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.Test.Model
{
    /// <summary>
    ///  Class for testing GetConnectionHealthResponseLiveness
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetConnectionHealthResponseLivenessTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetConnectionHealthResponseLiveness
        //private GetConnectionHealthResponseLiveness instance;

        public GetConnectionHealthResponseLivenessTests()
        {
            // TODO uncomment below to create an instance of GetConnectionHealthResponseLiveness
            //instance = new GetConnectionHealthResponseLiveness();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetConnectionHealthResponseLiveness
        /// </summary>
        [Fact]
        public void GetConnectionHealthResponseLivenessInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetConnectionHealthResponseLiveness
            //Assert.IsType<GetConnectionHealthResponseLiveness>(instance);
        }


        /// <summary>
        /// Test the property 'LastBrowserPushAt'
        /// </summary>
        [Fact]
        public void LastBrowserPushAtTest()
        {
            // TODO unit test for the property 'LastBrowserPushAt'
        }
        /// <summary>
        /// Test the property 'LastBrowserPushAgo'
        /// </summary>
        [Fact]
        public void LastBrowserPushAgoTest()
        {
            // TODO unit test for the property 'LastBrowserPushAgo'
        }
        /// <summary>
        /// Test the property 'LastSyncedAt'
        /// </summary>
        [Fact]
        public void LastSyncedAtTest()
        {
            // TODO unit test for the property 'LastSyncedAt'
        }
        /// <summary>
        /// Test the property 'LastUsedAt'
        /// </summary>
        [Fact]
        public void LastUsedAtTest()
        {
            // TODO unit test for the property 'LastUsedAt'
        }
        /// <summary>
        /// Test the property 'LastUsedAgo'
        /// </summary>
        [Fact]
        public void LastUsedAgoTest()
        {
            // TODO unit test for the property 'LastUsedAgo'
        }
        /// <summary>
        /// Test the property 'AuthFailureStreak'
        /// </summary>
        [Fact]
        public void AuthFailureStreakTest()
        {
            // TODO unit test for the property 'AuthFailureStreak'
        }

    }

}
