/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.Api;
using net.crossly.Model;
using net.crossly.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.Test.Model
{
    /// <summary>
    ///  Class for testing GetConnectionEmailResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetConnectionEmailResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetConnectionEmailResponseData
        //private GetConnectionEmailResponseData instance;

        public GetConnectionEmailResponseDataTests()
        {
            // TODO uncomment below to create an instance of GetConnectionEmailResponseData
            //instance = new GetConnectionEmailResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetConnectionEmailResponseData
        /// </summary>
        [Fact]
        public void GetConnectionEmailResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetConnectionEmailResponseData
            //Assert.IsType<GetConnectionEmailResponseData>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'IsConnected'
        /// </summary>
        [Fact]
        public void IsConnectedTest()
        {
            // TODO unit test for the property 'IsConnected'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Fact]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Fact]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'LastSyncedAt'
        /// </summary>
        [Fact]
        public void LastSyncedAtTest()
        {
            // TODO unit test for the property 'LastSyncedAt'
        }

    }

}
