/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.Api;
using net.crossly.Model;
using net.crossly.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.Test.Model
{
    /// <summary>
    ///  Class for testing GetOrderShipmentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetOrderShipmentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetOrderShipmentResponse
        //private GetOrderShipmentResponse instance;

        public GetOrderShipmentResponseTests()
        {
            // TODO uncomment below to create an instance of GetOrderShipmentResponse
            //instance = new GetOrderShipmentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetOrderShipmentResponse
        /// </summary>
        [Fact]
        public void GetOrderShipmentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetOrderShipmentResponse
            //Assert.IsType<GetOrderShipmentResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'TotalLabelCostCents'
        /// </summary>
        [Fact]
        public void TotalLabelCostCentsTest()
        {
            // TODO unit test for the property 'TotalLabelCostCents'
        }

    }

}
