/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.Api;
using net.crossly.Model;
using net.crossly.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.Test.Model
{
    /// <summary>
    ///  Class for testing ListAuthSessionsItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListAuthSessionsItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListAuthSessionsItem
        //private ListAuthSessionsItem instance;

        public ListAuthSessionsItemTests()
        {
            // TODO uncomment below to create an instance of ListAuthSessionsItem
            //instance = new ListAuthSessionsItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListAuthSessionsItem
        /// </summary>
        [Fact]
        public void ListAuthSessionsItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListAuthSessionsItem
            //Assert.IsType<ListAuthSessionsItem>(instance);
        }


        /// <summary>
        /// Test the property 'IsCurrent'
        /// </summary>
        [Fact]
        public void IsCurrentTest()
        {
            // TODO unit test for the property 'IsCurrent'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Fact]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Fact]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }
        /// <summary>
        /// Test the property 'IpCountry'
        /// </summary>
        [Fact]
        public void IpCountryTest()
        {
            // TODO unit test for the property 'IpCountry'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'LastUsedAt'
        /// </summary>
        [Fact]
        public void LastUsedAtTest()
        {
            // TODO unit test for the property 'LastUsedAt'
        }
        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

    }

}
