/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.Api;
using net.crossly.Model;
using net.crossly.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.Test.Model
{
    /// <summary>
    ///  Class for testing ListCbxDisbursementRulesItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListCbxDisbursementRulesItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListCbxDisbursementRulesItem
        //private ListCbxDisbursementRulesItem instance;

        public ListCbxDisbursementRulesItemTests()
        {
            // TODO uncomment below to create an instance of ListCbxDisbursementRulesItem
            //instance = new ListCbxDisbursementRulesItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListCbxDisbursementRulesItem
        /// </summary>
        [Fact]
        public void ListCbxDisbursementRulesItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListCbxDisbursementRulesItem
            //Assert.IsType<ListCbxDisbursementRulesItem>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ThresholdBaseUnits'
        /// </summary>
        [Fact]
        public void ThresholdBaseUnitsTest()
        {
            // TODO unit test for the property 'ThresholdBaseUnits'
        }
        /// <summary>
        /// Test the property 'DistributeBps'
        /// </summary>
        [Fact]
        public void DistributeBpsTest()
        {
            // TODO unit test for the property 'DistributeBps'
        }
        /// <summary>
        /// Test the property 'CheckCadenceHours'
        /// </summary>
        [Fact]
        public void CheckCadenceHoursTest()
        {
            // TODO unit test for the property 'CheckCadenceHours'
        }
        /// <summary>
        /// Test the property 'RequireCoverageBps'
        /// </summary>
        [Fact]
        public void RequireCoverageBpsTest()
        {
            // TODO unit test for the property 'RequireCoverageBps'
        }
        /// <summary>
        /// Test the property 'Metric'
        /// </summary>
        [Fact]
        public void MetricTest()
        {
            // TODO unit test for the property 'Metric'
        }
        /// <summary>
        /// Test the property 'LookbackDays'
        /// </summary>
        [Fact]
        public void LookbackDaysTest()
        {
            // TODO unit test for the property 'LookbackDays'
        }
        /// <summary>
        /// Test the property 'MaxRecipients'
        /// </summary>
        [Fact]
        public void MaxRecipientsTest()
        {
            // TODO unit test for the property 'MaxRecipients'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'LastFiredAt'
        /// </summary>
        [Fact]
        public void LastFiredAtTest()
        {
            // TODO unit test for the property 'LastFiredAt'
        }

    }

}
