/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using net.crossly.Client;
using net.crossly.Model;

namespace net.crossly.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICompWatchlistsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a sold-comp watchlist.
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CreateCompWatchlistResponse</returns>
        CreateCompWatchlistResponse CreateCompWatchlist();

        /// <summary>
        /// Create a sold-comp watchlist.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CreateCompWatchlistResponse</returns>
        ApiResponse<CreateCompWatchlistResponse> CreateCompWatchlistWithHttpInfo();
        /// <summary>
        /// Manually trigger a watchlist scrape.
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>CreateCompWatchlistScrapeResponse</returns>
        CreateCompWatchlistScrapeResponse CreateCompWatchlistScrape(Guid id);

        /// <summary>
        /// Manually trigger a watchlist scrape.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of CreateCompWatchlistScrapeResponse</returns>
        ApiResponse<CreateCompWatchlistScrapeResponse> CreateCompWatchlistScrapeWithHttpInfo(Guid id);
        /// <summary>
        /// Delete a sold-comp watchlist.
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>DeleteCompWatchlistResponse</returns>
        DeleteCompWatchlistResponse DeleteCompWatchlist(Guid id);

        /// <summary>
        /// Delete a sold-comp watchlist.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of DeleteCompWatchlistResponse</returns>
        ApiResponse<DeleteCompWatchlistResponse> DeleteCompWatchlistWithHttpInfo(Guid id);
        /// <summary>
        /// Recent external sold comps matching this watchlist.
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>V1List</returns>
        V1List ListCompWatchlistRecent(Guid id);

        /// <summary>
        /// Recent external sold comps matching this watchlist.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of V1List</returns>
        ApiResponse<V1List> ListCompWatchlistRecentWithHttpInfo(Guid id);
        /// <summary>
        /// List the seller&#39;s sold-comp watchlists.
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>V1List</returns>
        V1List ListCompWatchlists();

        /// <summary>
        /// List the seller&#39;s sold-comp watchlists.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of V1List</returns>
        ApiResponse<V1List> ListCompWatchlistsWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICompWatchlistsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a sold-comp watchlist.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateCompWatchlistResponse</returns>
        System.Threading.Tasks.Task<CreateCompWatchlistResponse> CreateCompWatchlistAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create a sold-comp watchlist.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateCompWatchlistResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateCompWatchlistResponse>> CreateCompWatchlistWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Manually trigger a watchlist scrape.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateCompWatchlistScrapeResponse</returns>
        System.Threading.Tasks.Task<CreateCompWatchlistScrapeResponse> CreateCompWatchlistScrapeAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Manually trigger a watchlist scrape.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateCompWatchlistScrapeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateCompWatchlistScrapeResponse>> CreateCompWatchlistScrapeWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete a sold-comp watchlist.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeleteCompWatchlistResponse</returns>
        System.Threading.Tasks.Task<DeleteCompWatchlistResponse> DeleteCompWatchlistAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete a sold-comp watchlist.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeleteCompWatchlistResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeleteCompWatchlistResponse>> DeleteCompWatchlistWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Recent external sold comps matching this watchlist.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1List</returns>
        System.Threading.Tasks.Task<V1List> ListCompWatchlistRecentAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Recent external sold comps matching this watchlist.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1List)</returns>
        System.Threading.Tasks.Task<ApiResponse<V1List>> ListCompWatchlistRecentWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List the seller&#39;s sold-comp watchlists.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1List</returns>
        System.Threading.Tasks.Task<V1List> ListCompWatchlistsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List the seller&#39;s sold-comp watchlists.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1List)</returns>
        System.Threading.Tasks.Task<ApiResponse<V1List>> ListCompWatchlistsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICompWatchlistsApi : ICompWatchlistsApiSync, ICompWatchlistsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CompWatchlistsApi : ICompWatchlistsApi
    {
        private net.crossly.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CompWatchlistsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CompWatchlistsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompWatchlistsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CompWatchlistsApi(string basePath)
        {
            this.Configuration = net.crossly.Client.Configuration.MergeConfigurations(
                net.crossly.Client.GlobalConfiguration.Instance,
                new net.crossly.Client.Configuration { BasePath = basePath }
            );
            this.Client = new net.crossly.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new net.crossly.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = net.crossly.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompWatchlistsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CompWatchlistsApi(net.crossly.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = net.crossly.Client.Configuration.MergeConfigurations(
                net.crossly.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new net.crossly.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new net.crossly.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = net.crossly.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompWatchlistsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public CompWatchlistsApi(net.crossly.Client.ISynchronousClient client, net.crossly.Client.IAsynchronousClient asyncClient, net.crossly.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = net.crossly.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public net.crossly.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public net.crossly.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public net.crossly.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public net.crossly.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a sold-comp watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CreateCompWatchlistResponse</returns>
        public CreateCompWatchlistResponse CreateCompWatchlist()
        {
            net.crossly.Client.ApiResponse<CreateCompWatchlistResponse> localVarResponse = CreateCompWatchlistWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a sold-comp watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CreateCompWatchlistResponse</returns>
        public net.crossly.Client.ApiResponse<CreateCompWatchlistResponse> CreateCompWatchlistWithHttpInfo()
        {
            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateCompWatchlistResponse>("/v1/comp-watchlists", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCompWatchlist", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a sold-comp watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateCompWatchlistResponse</returns>
        public async System.Threading.Tasks.Task<CreateCompWatchlistResponse> CreateCompWatchlistAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            net.crossly.Client.ApiResponse<CreateCompWatchlistResponse> localVarResponse = await CreateCompWatchlistWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a sold-comp watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateCompWatchlistResponse)</returns>
        public async System.Threading.Tasks.Task<net.crossly.Client.ApiResponse<CreateCompWatchlistResponse>> CreateCompWatchlistWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateCompWatchlistResponse>("/v1/comp-watchlists", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCompWatchlist", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Manually trigger a watchlist scrape. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>CreateCompWatchlistScrapeResponse</returns>
        public CreateCompWatchlistScrapeResponse CreateCompWatchlistScrape(Guid id)
        {
            net.crossly.Client.ApiResponse<CreateCompWatchlistScrapeResponse> localVarResponse = CreateCompWatchlistScrapeWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Manually trigger a watchlist scrape. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of CreateCompWatchlistScrapeResponse</returns>
        public net.crossly.Client.ApiResponse<CreateCompWatchlistScrapeResponse> CreateCompWatchlistScrapeWithHttpInfo(Guid id)
        {
            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", net.crossly.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateCompWatchlistScrapeResponse>("/v1/comp-watchlists/{id}/scrape", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCompWatchlistScrape", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Manually trigger a watchlist scrape. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateCompWatchlistScrapeResponse</returns>
        public async System.Threading.Tasks.Task<CreateCompWatchlistScrapeResponse> CreateCompWatchlistScrapeAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            net.crossly.Client.ApiResponse<CreateCompWatchlistScrapeResponse> localVarResponse = await CreateCompWatchlistScrapeWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Manually trigger a watchlist scrape. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateCompWatchlistScrapeResponse)</returns>
        public async System.Threading.Tasks.Task<net.crossly.Client.ApiResponse<CreateCompWatchlistScrapeResponse>> CreateCompWatchlistScrapeWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", net.crossly.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateCompWatchlistScrapeResponse>("/v1/comp-watchlists/{id}/scrape", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCompWatchlistScrape", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a sold-comp watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>DeleteCompWatchlistResponse</returns>
        public DeleteCompWatchlistResponse DeleteCompWatchlist(Guid id)
        {
            net.crossly.Client.ApiResponse<DeleteCompWatchlistResponse> localVarResponse = DeleteCompWatchlistWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a sold-comp watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of DeleteCompWatchlistResponse</returns>
        public net.crossly.Client.ApiResponse<DeleteCompWatchlistResponse> DeleteCompWatchlistWithHttpInfo(Guid id)
        {
            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", net.crossly.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<DeleteCompWatchlistResponse>("/v1/comp-watchlists/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteCompWatchlist", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a sold-comp watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeleteCompWatchlistResponse</returns>
        public async System.Threading.Tasks.Task<DeleteCompWatchlistResponse> DeleteCompWatchlistAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            net.crossly.Client.ApiResponse<DeleteCompWatchlistResponse> localVarResponse = await DeleteCompWatchlistWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a sold-comp watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeleteCompWatchlistResponse)</returns>
        public async System.Threading.Tasks.Task<net.crossly.Client.ApiResponse<DeleteCompWatchlistResponse>> DeleteCompWatchlistWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", net.crossly.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<DeleteCompWatchlistResponse>("/v1/comp-watchlists/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteCompWatchlist", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Recent external sold comps matching this watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>V1List</returns>
        public V1List ListCompWatchlistRecent(Guid id)
        {
            net.crossly.Client.ApiResponse<V1List> localVarResponse = ListCompWatchlistRecentWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Recent external sold comps matching this watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of V1List</returns>
        public net.crossly.Client.ApiResponse<V1List> ListCompWatchlistRecentWithHttpInfo(Guid id)
        {
            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", net.crossly.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<V1List>("/v1/comp-watchlists/{id}/recent", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCompWatchlistRecent", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Recent external sold comps matching this watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1List</returns>
        public async System.Threading.Tasks.Task<V1List> ListCompWatchlistRecentAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            net.crossly.Client.ApiResponse<V1List> localVarResponse = await ListCompWatchlistRecentWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Recent external sold comps matching this watchlist. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1List)</returns>
        public async System.Threading.Tasks.Task<net.crossly.Client.ApiResponse<V1List>> ListCompWatchlistRecentWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", net.crossly.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<V1List>("/v1/comp-watchlists/{id}/recent", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCompWatchlistRecent", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List the seller&#39;s sold-comp watchlists. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>V1List</returns>
        public V1List ListCompWatchlists()
        {
            net.crossly.Client.ApiResponse<V1List> localVarResponse = ListCompWatchlistsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List the seller&#39;s sold-comp watchlists. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of V1List</returns>
        public net.crossly.Client.ApiResponse<V1List> ListCompWatchlistsWithHttpInfo()
        {
            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<V1List>("/v1/comp-watchlists", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCompWatchlists", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List the seller&#39;s sold-comp watchlists. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1List</returns>
        public async System.Threading.Tasks.Task<V1List> ListCompWatchlistsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            net.crossly.Client.ApiResponse<V1List> localVarResponse = await ListCompWatchlistsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List the seller&#39;s sold-comp watchlists. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1List)</returns>
        public async System.Threading.Tasks.Task<net.crossly.Client.ApiResponse<V1List>> ListCompWatchlistsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<V1List>("/v1/comp-watchlists", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCompWatchlists", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
