/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using net.crossly.Client;
using net.crossly.Model;

namespace net.crossly.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPATApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Mint a new PAT. Full token returned ONCE — store it on the client.
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CreatePatResponse</returns>
        CreatePatResponse CreatePat();

        /// <summary>
        /// Mint a new PAT. Full token returned ONCE — store it on the client.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CreatePatResponse</returns>
        ApiResponse<CreatePatResponse> CreatePatWithHttpInfo();
        /// <summary>
        /// Revoke a PAT by id.
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>DeletePatResponse</returns>
        DeletePatResponse DeletePat(Guid id);

        /// <summary>
        /// Revoke a PAT by id.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of DeletePatResponse</returns>
        ApiResponse<DeletePatResponse> DeletePatWithHttpInfo(Guid id);
        /// <summary>
        /// List the canonical scope catalog.
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetPatScopeResponse</returns>
        GetPatScopeResponse GetPatScope();

        /// <summary>
        /// List the canonical scope catalog.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetPatScopeResponse</returns>
        ApiResponse<GetPatScopeResponse> GetPatScopeWithHttpInfo();
        /// <summary>
        /// List the caller&#39;s PATs (preview only).
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>V1List</returns>
        V1List ListPat();

        /// <summary>
        /// List the caller&#39;s PATs (preview only).
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of V1List</returns>
        ApiResponse<V1List> ListPatWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPATApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Mint a new PAT. Full token returned ONCE — store it on the client.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreatePatResponse</returns>
        System.Threading.Tasks.Task<CreatePatResponse> CreatePatAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Mint a new PAT. Full token returned ONCE — store it on the client.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreatePatResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreatePatResponse>> CreatePatWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Revoke a PAT by id.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeletePatResponse</returns>
        System.Threading.Tasks.Task<DeletePatResponse> DeletePatAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Revoke a PAT by id.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeletePatResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeletePatResponse>> DeletePatWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List the canonical scope catalog.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPatScopeResponse</returns>
        System.Threading.Tasks.Task<GetPatScopeResponse> GetPatScopeAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List the canonical scope catalog.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPatScopeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetPatScopeResponse>> GetPatScopeWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List the caller&#39;s PATs (preview only).
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1List</returns>
        System.Threading.Tasks.Task<V1List> ListPatAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List the caller&#39;s PATs (preview only).
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1List)</returns>
        System.Threading.Tasks.Task<ApiResponse<V1List>> ListPatWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPATApi : IPATApiSync, IPATApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PATApi : IPATApi
    {
        private net.crossly.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PATApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PATApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PATApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PATApi(string basePath)
        {
            this.Configuration = net.crossly.Client.Configuration.MergeConfigurations(
                net.crossly.Client.GlobalConfiguration.Instance,
                new net.crossly.Client.Configuration { BasePath = basePath }
            );
            this.Client = new net.crossly.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new net.crossly.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = net.crossly.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PATApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PATApi(net.crossly.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = net.crossly.Client.Configuration.MergeConfigurations(
                net.crossly.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new net.crossly.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new net.crossly.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = net.crossly.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PATApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public PATApi(net.crossly.Client.ISynchronousClient client, net.crossly.Client.IAsynchronousClient asyncClient, net.crossly.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = net.crossly.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public net.crossly.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public net.crossly.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public net.crossly.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public net.crossly.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Mint a new PAT. Full token returned ONCE — store it on the client. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CreatePatResponse</returns>
        public CreatePatResponse CreatePat()
        {
            net.crossly.Client.ApiResponse<CreatePatResponse> localVarResponse = CreatePatWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Mint a new PAT. Full token returned ONCE — store it on the client. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CreatePatResponse</returns>
        public net.crossly.Client.ApiResponse<CreatePatResponse> CreatePatWithHttpInfo()
        {
            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreatePatResponse>("/v1/pat", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePat", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Mint a new PAT. Full token returned ONCE — store it on the client. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreatePatResponse</returns>
        public async System.Threading.Tasks.Task<CreatePatResponse> CreatePatAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            net.crossly.Client.ApiResponse<CreatePatResponse> localVarResponse = await CreatePatWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Mint a new PAT. Full token returned ONCE — store it on the client. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreatePatResponse)</returns>
        public async System.Threading.Tasks.Task<net.crossly.Client.ApiResponse<CreatePatResponse>> CreatePatWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<CreatePatResponse>("/v1/pat", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePat", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke a PAT by id. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>DeletePatResponse</returns>
        public DeletePatResponse DeletePat(Guid id)
        {
            net.crossly.Client.ApiResponse<DeletePatResponse> localVarResponse = DeletePatWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revoke a PAT by id. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of DeletePatResponse</returns>
        public net.crossly.Client.ApiResponse<DeletePatResponse> DeletePatWithHttpInfo(Guid id)
        {
            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", net.crossly.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<DeletePatResponse>("/v1/pat/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeletePat", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke a PAT by id. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeletePatResponse</returns>
        public async System.Threading.Tasks.Task<DeletePatResponse> DeletePatAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            net.crossly.Client.ApiResponse<DeletePatResponse> localVarResponse = await DeletePatWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revoke a PAT by id. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeletePatResponse)</returns>
        public async System.Threading.Tasks.Task<net.crossly.Client.ApiResponse<DeletePatResponse>> DeletePatWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", net.crossly.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<DeletePatResponse>("/v1/pat/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeletePat", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List the canonical scope catalog. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetPatScopeResponse</returns>
        public GetPatScopeResponse GetPatScope()
        {
            net.crossly.Client.ApiResponse<GetPatScopeResponse> localVarResponse = GetPatScopeWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List the canonical scope catalog. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetPatScopeResponse</returns>
        public net.crossly.Client.ApiResponse<GetPatScopeResponse> GetPatScopeWithHttpInfo()
        {
            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetPatScopeResponse>("/v1/pat/scopes", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPatScope", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List the canonical scope catalog. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPatScopeResponse</returns>
        public async System.Threading.Tasks.Task<GetPatScopeResponse> GetPatScopeAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            net.crossly.Client.ApiResponse<GetPatScopeResponse> localVarResponse = await GetPatScopeWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List the canonical scope catalog. 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPatScopeResponse)</returns>
        public async System.Threading.Tasks.Task<net.crossly.Client.ApiResponse<GetPatScopeResponse>> GetPatScopeWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetPatScopeResponse>("/v1/pat/scopes", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPatScope", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List the caller&#39;s PATs (preview only). 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>V1List</returns>
        public V1List ListPat()
        {
            net.crossly.Client.ApiResponse<V1List> localVarResponse = ListPatWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List the caller&#39;s PATs (preview only). 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of V1List</returns>
        public net.crossly.Client.ApiResponse<V1List> ListPatWithHttpInfo()
        {
            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<V1List>("/v1/pat", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPat", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List the caller&#39;s PATs (preview only). 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1List</returns>
        public async System.Threading.Tasks.Task<V1List> ListPatAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            net.crossly.Client.ApiResponse<V1List> localVarResponse = await ListPatWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List the caller&#39;s PATs (preview only). 
        /// </summary>
        /// <exception cref="net.crossly.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1List)</returns>
        public async System.Threading.Tasks.Task<net.crossly.Client.ApiResponse<V1List>> ListPatWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            net.crossly.Client.RequestOptions localVarRequestOptions = new net.crossly.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = net.crossly.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = net.crossly.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<V1List>("/v1/pat", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPat", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
