/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.buyer.Client.OpenAPIDateConverter;

namespace net.crossly.buyer.Model
{
    /// <summary>
    /// CreateCbxRedemptionQuoteResponse
    /// </summary>
    [DataContract(Name = "CreateCbxRedemptionQuoteResponse")]
    public partial class CreateCbxRedemptionQuoteResponse : IEquatable<CreateCbxRedemptionQuoteResponse>, IValidatableObject
    {
        /// <summary>
        /// Defines ServiceKind
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ServiceKindEnum
        {
            /// <summary>
            /// Enum Grading for value: grading
            /// </summary>
            [EnumMember(Value = "grading")]
            Grading = 1,

            /// <summary>
            /// Enum Subscription for value: subscription
            /// </summary>
            [EnumMember(Value = "subscription")]
            Subscription = 2,

            /// <summary>
            /// Enum Authentication for value: authentication
            /// </summary>
            [EnumMember(Value = "authentication")]
            Authentication = 3,

            /// <summary>
            /// Enum EvidenceSeal for value: evidence_seal
            /// </summary>
            [EnumMember(Value = "evidence_seal")]
            EvidenceSeal = 4

        }


        /// <summary>
        /// Gets or Sets ServiceKind
        /// </summary>
        [DataMember(Name = "serviceKind", IsRequired = true, EmitDefaultValue = false)]
        public ServiceKindEnum ServiceKind { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCbxRedemptionQuoteResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateCbxRedemptionQuoteResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCbxRedemptionQuoteResponse" /> class.
        /// </summary>
        /// <param name="serviceKind">serviceKind (required).</param>
        /// <param name="label">label (required).</param>
        /// <param name="listPriceCents">listPriceCents (required).</param>
        /// <param name="chargedCents">chargedCents (required).</param>
        /// <param name="discountBps">discountBps (required).</param>
        /// <param name="baseUnits">baseUnits (required).</param>
        /// <param name="centsPerToken">centsPerToken (required).</param>
        public CreateCbxRedemptionQuoteResponse(ServiceKindEnum serviceKind = default(ServiceKindEnum), string label = default(string), decimal listPriceCents = default(decimal), decimal chargedCents = default(decimal), decimal discountBps = default(decimal), string baseUnits = default(string), decimal centsPerToken = default(decimal))
        {
            this.ServiceKind = serviceKind;
            // to ensure "label" is required (not null)
            if (label == null) {
                throw new ArgumentNullException("label is a required property for CreateCbxRedemptionQuoteResponse and cannot be null");
            }
            this.Label = label;
            this.ListPriceCents = listPriceCents;
            this.ChargedCents = chargedCents;
            this.DiscountBps = discountBps;
            // to ensure "baseUnits" is required (not null)
            if (baseUnits == null) {
                throw new ArgumentNullException("baseUnits is a required property for CreateCbxRedemptionQuoteResponse and cannot be null");
            }
            this.BaseUnits = baseUnits;
            this.CentsPerToken = centsPerToken;
        }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [DataMember(Name = "label", IsRequired = true, EmitDefaultValue = false)]
        public string Label { get; set; }

        /// <summary>
        /// Gets or Sets ListPriceCents
        /// </summary>
        [DataMember(Name = "listPriceCents", IsRequired = true, EmitDefaultValue = false)]
        public decimal ListPriceCents { get; set; }

        /// <summary>
        /// Gets or Sets ChargedCents
        /// </summary>
        [DataMember(Name = "chargedCents", IsRequired = true, EmitDefaultValue = false)]
        public decimal ChargedCents { get; set; }

        /// <summary>
        /// Gets or Sets DiscountBps
        /// </summary>
        [DataMember(Name = "discountBps", IsRequired = true, EmitDefaultValue = false)]
        public decimal DiscountBps { get; set; }

        /// <summary>
        /// Gets or Sets BaseUnits
        /// </summary>
        [DataMember(Name = "baseUnits", IsRequired = true, EmitDefaultValue = false)]
        public string BaseUnits { get; set; }

        /// <summary>
        /// Gets or Sets CentsPerToken
        /// </summary>
        [DataMember(Name = "centsPerToken", IsRequired = true, EmitDefaultValue = false)]
        public decimal CentsPerToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateCbxRedemptionQuoteResponse {\n");
            sb.Append("  ServiceKind: ").Append(ServiceKind).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  ListPriceCents: ").Append(ListPriceCents).Append("\n");
            sb.Append("  ChargedCents: ").Append(ChargedCents).Append("\n");
            sb.Append("  DiscountBps: ").Append(DiscountBps).Append("\n");
            sb.Append("  BaseUnits: ").Append(BaseUnits).Append("\n");
            sb.Append("  CentsPerToken: ").Append(CentsPerToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateCbxRedemptionQuoteResponse);
        }

        /// <summary>
        /// Returns true if CreateCbxRedemptionQuoteResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateCbxRedemptionQuoteResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCbxRedemptionQuoteResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ServiceKind == input.ServiceKind ||
                    this.ServiceKind.Equals(input.ServiceKind)
                ) && 
                (
                    this.Label == input.Label ||
                    (this.Label != null &&
                    this.Label.Equals(input.Label))
                ) && 
                (
                    this.ListPriceCents == input.ListPriceCents ||
                    this.ListPriceCents.Equals(input.ListPriceCents)
                ) && 
                (
                    this.ChargedCents == input.ChargedCents ||
                    this.ChargedCents.Equals(input.ChargedCents)
                ) && 
                (
                    this.DiscountBps == input.DiscountBps ||
                    this.DiscountBps.Equals(input.DiscountBps)
                ) && 
                (
                    this.BaseUnits == input.BaseUnits ||
                    (this.BaseUnits != null &&
                    this.BaseUnits.Equals(input.BaseUnits))
                ) && 
                (
                    this.CentsPerToken == input.CentsPerToken ||
                    this.CentsPerToken.Equals(input.CentsPerToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ServiceKind.GetHashCode();
                if (this.Label != null)
                {
                    hashCode = (hashCode * 59) + this.Label.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ListPriceCents.GetHashCode();
                hashCode = (hashCode * 59) + this.ChargedCents.GetHashCode();
                hashCode = (hashCode * 59) + this.DiscountBps.GetHashCode();
                if (this.BaseUnits != null)
                {
                    hashCode = (hashCode * 59) + this.BaseUnits.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.CentsPerToken.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
