/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.buyer.Client.OpenAPIDateConverter;

namespace net.crossly.buyer.Model
{
    /// <summary>
    /// CreateCbxCampaignExecuteResponse
    /// </summary>
    [DataContract(Name = "CreateCbxCampaignExecuteResponse")]
    public partial class CreateCbxCampaignExecuteResponse : IEquatable<CreateCbxCampaignExecuteResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCbxCampaignExecuteResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateCbxCampaignExecuteResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCbxCampaignExecuteResponse" /> class.
        /// </summary>
        /// <param name="paidCount">paidCount (required).</param>
        /// <param name="paidBaseUnits">paidBaseUnits (required).</param>
        public CreateCbxCampaignExecuteResponse(decimal paidCount = default(decimal), string paidBaseUnits = default(string))
        {
            this.PaidCount = paidCount;
            // to ensure "paidBaseUnits" is required (not null)
            if (paidBaseUnits == null) {
                throw new ArgumentNullException("paidBaseUnits is a required property for CreateCbxCampaignExecuteResponse and cannot be null");
            }
            this.PaidBaseUnits = paidBaseUnits;
        }

        /// <summary>
        /// Gets or Sets PaidCount
        /// </summary>
        [DataMember(Name = "paidCount", IsRequired = true, EmitDefaultValue = false)]
        public decimal PaidCount { get; set; }

        /// <summary>
        /// Gets or Sets PaidBaseUnits
        /// </summary>
        [DataMember(Name = "paidBaseUnits", IsRequired = true, EmitDefaultValue = false)]
        public string PaidBaseUnits { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateCbxCampaignExecuteResponse {\n");
            sb.Append("  PaidCount: ").Append(PaidCount).Append("\n");
            sb.Append("  PaidBaseUnits: ").Append(PaidBaseUnits).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateCbxCampaignExecuteResponse);
        }

        /// <summary>
        /// Returns true if CreateCbxCampaignExecuteResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateCbxCampaignExecuteResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCbxCampaignExecuteResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PaidCount == input.PaidCount ||
                    this.PaidCount.Equals(input.PaidCount)
                ) && 
                (
                    this.PaidBaseUnits == input.PaidBaseUnits ||
                    (this.PaidBaseUnits != null &&
                    this.PaidBaseUnits.Equals(input.PaidBaseUnits))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.PaidCount.GetHashCode();
                if (this.PaidBaseUnits != null)
                {
                    hashCode = (hashCode * 59) + this.PaidBaseUnits.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
