/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.buyer.Client.OpenAPIDateConverter;

namespace net.crossly.buyer.Model
{
    /// <summary>
    /// CreateAiGenerateListingResponseSuggestedPrice
    /// </summary>
    [DataContract(Name = "CreateAiGenerateListingResponse_suggestedPrice")]
    public partial class CreateAiGenerateListingResponseSuggestedPrice : IEquatable<CreateAiGenerateListingResponseSuggestedPrice>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAiGenerateListingResponseSuggestedPrice" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateAiGenerateListingResponseSuggestedPrice() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAiGenerateListingResponseSuggestedPrice" /> class.
        /// </summary>
        /// <param name="value">value (required).</param>
        /// <param name="confidence">confidence (required).</param>
        public CreateAiGenerateListingResponseSuggestedPrice(decimal value = default(decimal), decimal confidence = default(decimal))
        {
            this.Value = value;
            this.Confidence = confidence;
        }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = false)]
        public decimal Value { get; set; }

        /// <summary>
        /// Gets or Sets Confidence
        /// </summary>
        [DataMember(Name = "confidence", IsRequired = true, EmitDefaultValue = false)]
        public decimal Confidence { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateAiGenerateListingResponseSuggestedPrice {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Confidence: ").Append(Confidence).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateAiGenerateListingResponseSuggestedPrice);
        }

        /// <summary>
        /// Returns true if CreateAiGenerateListingResponseSuggestedPrice instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateAiGenerateListingResponseSuggestedPrice to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateAiGenerateListingResponseSuggestedPrice input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Value == input.Value ||
                    this.Value.Equals(input.Value)
                ) && 
                (
                    this.Confidence == input.Confidence ||
                    this.Confidence.Equals(input.Confidence)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Value.GetHashCode();
                hashCode = (hashCode * 59) + this.Confidence.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
