/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.buyer.Client.OpenAPIDateConverter;

namespace net.crossly.buyer.Model
{
    /// <summary>
    /// GetAnalyticDashboardResponseRevenue
    /// </summary>
    [DataContract(Name = "GetAnalyticDashboardResponse_revenue")]
    public partial class GetAnalyticDashboardResponseRevenue : IEquatable<GetAnalyticDashboardResponseRevenue>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAnalyticDashboardResponseRevenue" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetAnalyticDashboardResponseRevenue() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAnalyticDashboardResponseRevenue" /> class.
        /// </summary>
        /// <param name="current">current (required).</param>
        /// <param name="previous">previous (required).</param>
        /// <param name="pctChange">pctChange.</param>
        public GetAnalyticDashboardResponseRevenue(decimal current = default(decimal), decimal previous = default(decimal), decimal? pctChange = default(decimal?))
        {
            this.Current = current;
            this.Previous = previous;
            this.PctChange = pctChange;
        }

        /// <summary>
        /// Gets or Sets Current
        /// </summary>
        [DataMember(Name = "current", IsRequired = true, EmitDefaultValue = false)]
        public decimal Current { get; set; }

        /// <summary>
        /// Gets or Sets Previous
        /// </summary>
        [DataMember(Name = "previous", IsRequired = true, EmitDefaultValue = false)]
        public decimal Previous { get; set; }

        /// <summary>
        /// Gets or Sets PctChange
        /// </summary>
        [DataMember(Name = "pctChange", EmitDefaultValue = true)]
        public decimal? PctChange { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetAnalyticDashboardResponseRevenue {\n");
            sb.Append("  Current: ").Append(Current).Append("\n");
            sb.Append("  Previous: ").Append(Previous).Append("\n");
            sb.Append("  PctChange: ").Append(PctChange).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetAnalyticDashboardResponseRevenue);
        }

        /// <summary>
        /// Returns true if GetAnalyticDashboardResponseRevenue instances are equal
        /// </summary>
        /// <param name="input">Instance of GetAnalyticDashboardResponseRevenue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetAnalyticDashboardResponseRevenue input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Current == input.Current ||
                    this.Current.Equals(input.Current)
                ) && 
                (
                    this.Previous == input.Previous ||
                    this.Previous.Equals(input.Previous)
                ) && 
                (
                    this.PctChange == input.PctChange ||
                    (this.PctChange != null &&
                    this.PctChange.Equals(input.PctChange))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Current.GetHashCode();
                hashCode = (hashCode * 59) + this.Previous.GetHashCode();
                if (this.PctChange != null)
                {
                    hashCode = (hashCode * 59) + this.PctChange.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
