/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.buyer.Client.OpenAPIDateConverter;

namespace net.crossly.buyer.Model
{
    /// <summary>
    /// GetCbxSubjectWalletResponse
    /// </summary>
    [DataContract(Name = "GetCbxSubjectWalletResponse")]
    public partial class GetCbxSubjectWalletResponse : IEquatable<GetCbxSubjectWalletResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCbxSubjectWalletResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetCbxSubjectWalletResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCbxSubjectWalletResponse" /> class.
        /// </summary>
        /// <param name="walletId">walletId (required).</param>
        /// <param name="address">address (required).</param>
        /// <param name="chain">chain (required).</param>
        /// <param name="verifiedAt">verifiedAt.</param>
        public GetCbxSubjectWalletResponse(string walletId = default(string), string address = default(string), string chain = default(string), DateTime? verifiedAt = default(DateTime?))
        {
            // to ensure "walletId" is required (not null)
            if (walletId == null) {
                throw new ArgumentNullException("walletId is a required property for GetCbxSubjectWalletResponse and cannot be null");
            }
            this.WalletId = walletId;
            // to ensure "address" is required (not null)
            if (address == null) {
                throw new ArgumentNullException("address is a required property for GetCbxSubjectWalletResponse and cannot be null");
            }
            this.Address = address;
            // to ensure "chain" is required (not null)
            if (chain == null) {
                throw new ArgumentNullException("chain is a required property for GetCbxSubjectWalletResponse and cannot be null");
            }
            this.Chain = chain;
            this.VerifiedAt = verifiedAt;
        }

        /// <summary>
        /// Gets or Sets WalletId
        /// </summary>
        [DataMember(Name = "walletId", IsRequired = true, EmitDefaultValue = false)]
        public string WalletId { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name = "address", IsRequired = true, EmitDefaultValue = false)]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets Chain
        /// </summary>
        [DataMember(Name = "chain", IsRequired = true, EmitDefaultValue = false)]
        public string Chain { get; set; }

        /// <summary>
        /// Gets or Sets VerifiedAt
        /// </summary>
        [DataMember(Name = "verifiedAt", EmitDefaultValue = true)]
        public DateTime? VerifiedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetCbxSubjectWalletResponse {\n");
            sb.Append("  WalletId: ").Append(WalletId).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Chain: ").Append(Chain).Append("\n");
            sb.Append("  VerifiedAt: ").Append(VerifiedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetCbxSubjectWalletResponse);
        }

        /// <summary>
        /// Returns true if GetCbxSubjectWalletResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetCbxSubjectWalletResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetCbxSubjectWalletResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.WalletId == input.WalletId ||
                    (this.WalletId != null &&
                    this.WalletId.Equals(input.WalletId))
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.Chain == input.Chain ||
                    (this.Chain != null &&
                    this.Chain.Equals(input.Chain))
                ) && 
                (
                    this.VerifiedAt == input.VerifiedAt ||
                    (this.VerifiedAt != null &&
                    this.VerifiedAt.Equals(input.VerifiedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WalletId != null)
                {
                    hashCode = (hashCode * 59) + this.WalletId.GetHashCode();
                }
                if (this.Address != null)
                {
                    hashCode = (hashCode * 59) + this.Address.GetHashCode();
                }
                if (this.Chain != null)
                {
                    hashCode = (hashCode * 59) + this.Chain.GetHashCode();
                }
                if (this.VerifiedAt != null)
                {
                    hashCode = (hashCode * 59) + this.VerifiedAt.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
