/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.buyer.Client.OpenAPIDateConverter;

namespace net.crossly.buyer.Model
{
    /// <summary>
    /// GetOfferResponse
    /// </summary>
    [DataContract(Name = "GetOfferResponse")]
    public partial class GetOfferResponse : IEquatable<GetOfferResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetOfferResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetOfferResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetOfferResponse" /> class.
        /// </summary>
        /// <param name="offers">offers (required).</param>
        public GetOfferResponse(List<GetOfferResponseOffers> offers = default(List<GetOfferResponseOffers>))
        {
            // to ensure "offers" is required (not null)
            if (offers == null) {
                throw new ArgumentNullException("offers is a required property for GetOfferResponse and cannot be null");
            }
            this.Offers = offers;
        }

        /// <summary>
        /// Gets or Sets Offers
        /// </summary>
        [DataMember(Name = "offers", IsRequired = true, EmitDefaultValue = false)]
        public List<GetOfferResponseOffers> Offers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetOfferResponse {\n");
            sb.Append("  Offers: ").Append(Offers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetOfferResponse);
        }

        /// <summary>
        /// Returns true if GetOfferResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetOfferResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetOfferResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Offers == input.Offers ||
                    this.Offers != null &&
                    input.Offers != null &&
                    this.Offers.SequenceEqual(input.Offers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Offers != null)
                {
                    hashCode = (hashCode * 59) + this.Offers.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
