/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.buyer.Client.OpenAPIDateConverter;

namespace net.crossly.buyer.Model
{
    /// <summary>
    /// GetOauthInitResponseOneOf1
    /// </summary>
    [DataContract(Name = "GetOauthInitResponse_oneOf_1")]
    public partial class GetOauthInitResponseOneOf1 : IEquatable<GetOauthInitResponseOneOf1>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetOauthInitResponseOneOf1" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetOauthInitResponseOneOf1() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetOauthInitResponseOneOf1" /> class.
        /// </summary>
        /// <param name="url">url (required).</param>
        /// <param name="correlationId">correlationId (required).</param>
        public GetOauthInitResponseOneOf1(string url = default(string), string correlationId = default(string))
        {
            // to ensure "url" is required (not null)
            if (url == null) {
                throw new ArgumentNullException("url is a required property for GetOauthInitResponseOneOf1 and cannot be null");
            }
            this.Url = url;
            // to ensure "correlationId" is required (not null)
            if (correlationId == null) {
                throw new ArgumentNullException("correlationId is a required property for GetOauthInitResponseOneOf1 and cannot be null");
            }
            this.CorrelationId = correlationId;
        }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets CorrelationId
        /// </summary>
        [DataMember(Name = "correlationId", IsRequired = true, EmitDefaultValue = false)]
        public string CorrelationId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetOauthInitResponseOneOf1 {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  CorrelationId: ").Append(CorrelationId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetOauthInitResponseOneOf1);
        }

        /// <summary>
        /// Returns true if GetOauthInitResponseOneOf1 instances are equal
        /// </summary>
        /// <param name="input">Instance of GetOauthInitResponseOneOf1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetOauthInitResponseOneOf1 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                ) && 
                (
                    this.CorrelationId == input.CorrelationId ||
                    (this.CorrelationId != null &&
                    this.CorrelationId.Equals(input.CorrelationId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Url != null)
                {
                    hashCode = (hashCode * 59) + this.Url.GetHashCode();
                }
                if (this.CorrelationId != null)
                {
                    hashCode = (hashCode * 59) + this.CorrelationId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
