/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.buyer.Client.OpenAPIDateConverter;

namespace net.crossly.buyer.Model
{
    /// <summary>
    /// GetPatternResponse
    /// </summary>
    [DataContract(Name = "GetPatternResponse")]
    public partial class GetPatternResponse : IEquatable<GetPatternResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetPatternResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetPatternResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetPatternResponse" /> class.
        /// </summary>
        /// <param name="patterns">patterns (required).</param>
        public GetPatternResponse(List<string> patterns = default(List<string>))
        {
            // to ensure "patterns" is required (not null)
            if (patterns == null) {
                throw new ArgumentNullException("patterns is a required property for GetPatternResponse and cannot be null");
            }
            this.Patterns = patterns;
        }

        /// <summary>
        /// Gets or Sets Patterns
        /// </summary>
        [DataMember(Name = "patterns", IsRequired = true, EmitDefaultValue = false)]
        public List<string> Patterns { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetPatternResponse {\n");
            sb.Append("  Patterns: ").Append(Patterns).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetPatternResponse);
        }

        /// <summary>
        /// Returns true if GetPatternResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetPatternResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetPatternResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Patterns == input.Patterns ||
                    this.Patterns != null &&
                    input.Patterns != null &&
                    this.Patterns.SequenceEqual(input.Patterns)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Patterns != null)
                {
                    hashCode = (hashCode * 59) + this.Patterns.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
