/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.buyer.Client.OpenAPIDateConverter;

namespace net.crossly.buyer.Model
{
    /// <summary>
    /// ListTaxonomySuggestItemCatalog
    /// </summary>
    [DataContract(Name = "ListTaxonomySuggestItem_catalog")]
    public partial class ListTaxonomySuggestItemCatalog : IEquatable<ListTaxonomySuggestItemCatalog>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListTaxonomySuggestItemCatalog" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListTaxonomySuggestItemCatalog() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListTaxonomySuggestItemCatalog" /> class.
        /// </summary>
        /// <param name="department">department (required).</param>
        /// <param name="category">category (required).</param>
        /// <param name="categoryFeatures">categoryFeatures (required).</param>
        public ListTaxonomySuggestItemCatalog(string department = default(string), string category = default(string), List<string> categoryFeatures = default(List<string>))
        {
            // to ensure "department" is required (not null)
            if (department == null) {
                throw new ArgumentNullException("department is a required property for ListTaxonomySuggestItemCatalog and cannot be null");
            }
            this.Department = department;
            // to ensure "category" is required (not null)
            if (category == null) {
                throw new ArgumentNullException("category is a required property for ListTaxonomySuggestItemCatalog and cannot be null");
            }
            this.Category = category;
            // to ensure "categoryFeatures" is required (not null)
            if (categoryFeatures == null) {
                throw new ArgumentNullException("categoryFeatures is a required property for ListTaxonomySuggestItemCatalog and cannot be null");
            }
            this.CategoryFeatures = categoryFeatures;
        }

        /// <summary>
        /// Gets or Sets Department
        /// </summary>
        [DataMember(Name = "department", IsRequired = true, EmitDefaultValue = false)]
        public string Department { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name = "category", IsRequired = true, EmitDefaultValue = false)]
        public string Category { get; set; }

        /// <summary>
        /// Gets or Sets CategoryFeatures
        /// </summary>
        [DataMember(Name = "category_features", IsRequired = true, EmitDefaultValue = false)]
        public List<string> CategoryFeatures { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListTaxonomySuggestItemCatalog {\n");
            sb.Append("  Department: ").Append(Department).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  CategoryFeatures: ").Append(CategoryFeatures).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListTaxonomySuggestItemCatalog);
        }

        /// <summary>
        /// Returns true if ListTaxonomySuggestItemCatalog instances are equal
        /// </summary>
        /// <param name="input">Instance of ListTaxonomySuggestItemCatalog to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListTaxonomySuggestItemCatalog input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Department == input.Department ||
                    (this.Department != null &&
                    this.Department.Equals(input.Department))
                ) && 
                (
                    this.Category == input.Category ||
                    (this.Category != null &&
                    this.Category.Equals(input.Category))
                ) && 
                (
                    this.CategoryFeatures == input.CategoryFeatures ||
                    this.CategoryFeatures != null &&
                    input.CategoryFeatures != null &&
                    this.CategoryFeatures.SequenceEqual(input.CategoryFeatures)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Department != null)
                {
                    hashCode = (hashCode * 59) + this.Department.GetHashCode();
                }
                if (this.Category != null)
                {
                    hashCode = (hashCode * 59) + this.Category.GetHashCode();
                }
                if (this.CategoryFeatures != null)
                {
                    hashCode = (hashCode * 59) + this.CategoryFeatures.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
