/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.buyer.Client.OpenAPIDateConverter;

namespace net.crossly.buyer.Model
{
    /// <summary>
    /// ListRestockPromptsItem
    /// </summary>
    [DataContract(Name = "ListRestockPromptsItem")]
    public partial class ListRestockPromptsItem : IEquatable<ListRestockPromptsItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListRestockPromptsItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListRestockPromptsItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListRestockPromptsItem" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="listingId">listingId (required).</param>
        /// <param name="inventoryItemId">inventoryItemId.</param>
        /// <param name="platforms">platforms (required).</param>
        /// <param name="newQuantity">newQuantity (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="listingTitle">listingTitle.</param>
        /// <param name="listingImages">listingImages.</param>
        /// <param name="listingPrice">listingPrice.</param>
        public ListRestockPromptsItem(string id = default(string), string listingId = default(string), string inventoryItemId = default(string), List<string> platforms = default(List<string>), decimal newQuantity = default(decimal), DateTime createdAt = default(DateTime), string listingTitle = default(string), List<string> listingImages = default(List<string>), string listingPrice = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null) {
                throw new ArgumentNullException("id is a required property for ListRestockPromptsItem and cannot be null");
            }
            this.Id = id;
            // to ensure "listingId" is required (not null)
            if (listingId == null) {
                throw new ArgumentNullException("listingId is a required property for ListRestockPromptsItem and cannot be null");
            }
            this.ListingId = listingId;
            // to ensure "platforms" is required (not null)
            if (platforms == null) {
                throw new ArgumentNullException("platforms is a required property for ListRestockPromptsItem and cannot be null");
            }
            this.Platforms = platforms;
            this.NewQuantity = newQuantity;
            this.CreatedAt = createdAt;
            this.InventoryItemId = inventoryItemId;
            this.ListingTitle = listingTitle;
            this.ListingImages = listingImages;
            this.ListingPrice = listingPrice;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets ListingId
        /// </summary>
        [DataMember(Name = "listingId", IsRequired = true, EmitDefaultValue = false)]
        public string ListingId { get; set; }

        /// <summary>
        /// Gets or Sets InventoryItemId
        /// </summary>
        [DataMember(Name = "inventoryItemId", EmitDefaultValue = true)]
        public string InventoryItemId { get; set; }

        /// <summary>
        /// Gets or Sets Platforms
        /// </summary>
        [DataMember(Name = "platforms", IsRequired = true, EmitDefaultValue = false)]
        public List<string> Platforms { get; set; }

        /// <summary>
        /// Gets or Sets NewQuantity
        /// </summary>
        [DataMember(Name = "newQuantity", IsRequired = true, EmitDefaultValue = false)]
        public decimal NewQuantity { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets ListingTitle
        /// </summary>
        [DataMember(Name = "listingTitle", EmitDefaultValue = true)]
        public string ListingTitle { get; set; }

        /// <summary>
        /// Gets or Sets ListingImages
        /// </summary>
        [DataMember(Name = "listingImages", EmitDefaultValue = true)]
        public List<string> ListingImages { get; set; }

        /// <summary>
        /// Gets or Sets ListingPrice
        /// </summary>
        [DataMember(Name = "listingPrice", EmitDefaultValue = true)]
        public string ListingPrice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListRestockPromptsItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ListingId: ").Append(ListingId).Append("\n");
            sb.Append("  InventoryItemId: ").Append(InventoryItemId).Append("\n");
            sb.Append("  Platforms: ").Append(Platforms).Append("\n");
            sb.Append("  NewQuantity: ").Append(NewQuantity).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  ListingTitle: ").Append(ListingTitle).Append("\n");
            sb.Append("  ListingImages: ").Append(ListingImages).Append("\n");
            sb.Append("  ListingPrice: ").Append(ListingPrice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListRestockPromptsItem);
        }

        /// <summary>
        /// Returns true if ListRestockPromptsItem instances are equal
        /// </summary>
        /// <param name="input">Instance of ListRestockPromptsItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListRestockPromptsItem input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ListingId == input.ListingId ||
                    (this.ListingId != null &&
                    this.ListingId.Equals(input.ListingId))
                ) && 
                (
                    this.InventoryItemId == input.InventoryItemId ||
                    (this.InventoryItemId != null &&
                    this.InventoryItemId.Equals(input.InventoryItemId))
                ) && 
                (
                    this.Platforms == input.Platforms ||
                    this.Platforms != null &&
                    input.Platforms != null &&
                    this.Platforms.SequenceEqual(input.Platforms)
                ) && 
                (
                    this.NewQuantity == input.NewQuantity ||
                    this.NewQuantity.Equals(input.NewQuantity)
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.ListingTitle == input.ListingTitle ||
                    (this.ListingTitle != null &&
                    this.ListingTitle.Equals(input.ListingTitle))
                ) && 
                (
                    this.ListingImages == input.ListingImages ||
                    this.ListingImages != null &&
                    input.ListingImages != null &&
                    this.ListingImages.SequenceEqual(input.ListingImages)
                ) && 
                (
                    this.ListingPrice == input.ListingPrice ||
                    (this.ListingPrice != null &&
                    this.ListingPrice.Equals(input.ListingPrice))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.ListingId != null)
                {
                    hashCode = (hashCode * 59) + this.ListingId.GetHashCode();
                }
                if (this.InventoryItemId != null)
                {
                    hashCode = (hashCode * 59) + this.InventoryItemId.GetHashCode();
                }
                if (this.Platforms != null)
                {
                    hashCode = (hashCode * 59) + this.Platforms.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.NewQuantity.GetHashCode();
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.ListingTitle != null)
                {
                    hashCode = (hashCode * 59) + this.ListingTitle.GetHashCode();
                }
                if (this.ListingImages != null)
                {
                    hashCode = (hashCode * 59) + this.ListingImages.GetHashCode();
                }
                if (this.ListingPrice != null)
                {
                    hashCode = (hashCode * 59) + this.ListingPrice.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
