/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.buyer.Client.OpenAPIDateConverter;

namespace net.crossly.buyer.Model
{
    /// <summary>
    /// ListBuyerCartItem
    /// </summary>
    [DataContract(Name = "ListBuyerCartItem")]
    public partial class ListBuyerCartItem : IEquatable<ListBuyerCartItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListBuyerCartItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListBuyerCartItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListBuyerCartItem" /> class.
        /// </summary>
        /// <param name="available">available (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="platformListingId">platformListingId (required).</param>
        /// <param name="quantity">quantity (required).</param>
        /// <param name="unitPriceCents">unitPriceCents (required).</param>
        /// <param name="slug">slug.</param>
        /// <param name="title">title.</param>
        /// <param name="listingStatus">listingStatus.</param>
        public ListBuyerCartItem(bool available = default(bool), string id = default(string), string platformListingId = default(string), decimal quantity = default(decimal), decimal unitPriceCents = default(decimal), string slug = default(string), string title = default(string), string listingStatus = default(string))
        {
            this.Available = available;
            // to ensure "id" is required (not null)
            if (id == null) {
                throw new ArgumentNullException("id is a required property for ListBuyerCartItem and cannot be null");
            }
            this.Id = id;
            // to ensure "platformListingId" is required (not null)
            if (platformListingId == null) {
                throw new ArgumentNullException("platformListingId is a required property for ListBuyerCartItem and cannot be null");
            }
            this.PlatformListingId = platformListingId;
            this.Quantity = quantity;
            this.UnitPriceCents = unitPriceCents;
            this.Slug = slug;
            this.Title = title;
            this.ListingStatus = listingStatus;
        }

        /// <summary>
        /// Gets or Sets Available
        /// </summary>
        [DataMember(Name = "available", IsRequired = true, EmitDefaultValue = true)]
        public bool Available { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets PlatformListingId
        /// </summary>
        [DataMember(Name = "platformListingId", IsRequired = true, EmitDefaultValue = false)]
        public string PlatformListingId { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name = "quantity", IsRequired = true, EmitDefaultValue = false)]
        public decimal Quantity { get; set; }

        /// <summary>
        /// Gets or Sets UnitPriceCents
        /// </summary>
        [DataMember(Name = "unitPriceCents", IsRequired = true, EmitDefaultValue = false)]
        public decimal UnitPriceCents { get; set; }

        /// <summary>
        /// Gets or Sets Slug
        /// </summary>
        [DataMember(Name = "slug", EmitDefaultValue = true)]
        public string Slug { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets ListingStatus
        /// </summary>
        [DataMember(Name = "listingStatus", EmitDefaultValue = true)]
        public string ListingStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListBuyerCartItem {\n");
            sb.Append("  Available: ").Append(Available).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PlatformListingId: ").Append(PlatformListingId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  UnitPriceCents: ").Append(UnitPriceCents).Append("\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  ListingStatus: ").Append(ListingStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListBuyerCartItem);
        }

        /// <summary>
        /// Returns true if ListBuyerCartItem instances are equal
        /// </summary>
        /// <param name="input">Instance of ListBuyerCartItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListBuyerCartItem input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Available == input.Available ||
                    this.Available.Equals(input.Available)
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.PlatformListingId == input.PlatformListingId ||
                    (this.PlatformListingId != null &&
                    this.PlatformListingId.Equals(input.PlatformListingId))
                ) && 
                (
                    this.Quantity == input.Quantity ||
                    this.Quantity.Equals(input.Quantity)
                ) && 
                (
                    this.UnitPriceCents == input.UnitPriceCents ||
                    this.UnitPriceCents.Equals(input.UnitPriceCents)
                ) && 
                (
                    this.Slug == input.Slug ||
                    (this.Slug != null &&
                    this.Slug.Equals(input.Slug))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.ListingStatus == input.ListingStatus ||
                    (this.ListingStatus != null &&
                    this.ListingStatus.Equals(input.ListingStatus))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Available.GetHashCode();
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.PlatformListingId != null)
                {
                    hashCode = (hashCode * 59) + this.PlatformListingId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Quantity.GetHashCode();
                hashCode = (hashCode * 59) + this.UnitPriceCents.GetHashCode();
                if (this.Slug != null)
                {
                    hashCode = (hashCode * 59) + this.Slug.GetHashCode();
                }
                if (this.Title != null)
                {
                    hashCode = (hashCode * 59) + this.Title.GetHashCode();
                }
                if (this.ListingStatus != null)
                {
                    hashCode = (hashCode * 59) + this.ListingStatus.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
