/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.Client.OpenAPIDateConverter;

namespace net.crossly.Model
{
    /// <summary>
    /// CreateCompWatchlistResponse
    /// </summary>
    [DataContract(Name = "CreateCompWatchlistResponse")]
    public partial class CreateCompWatchlistResponse : IEquatable<CreateCompWatchlistResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCompWatchlistResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateCompWatchlistResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCompWatchlistResponse" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="brand">brand.</param>
        /// <param name="name">name (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="userId">userId (required).</param>
        /// <param name="condition">condition.</param>
        /// <param name="categoryMain">categoryMain.</param>
        /// <param name="platform">platform.</param>
        /// <param name="minPrice">minPrice.</param>
        /// <param name="maxPrice">maxPrice.</param>
        /// <param name="lastMatchedAt">lastMatchedAt.</param>
        /// <param name="lastScrapedAt">lastScrapedAt.</param>
        public CreateCompWatchlistResponse(string id = default(string), string brand = default(string), string name = default(string), DateTime createdAt = default(DateTime), string userId = default(string), string condition = default(string), string categoryMain = default(string), string platform = default(string), string minPrice = default(string), string maxPrice = default(string), DateTime? lastMatchedAt = default(DateTime?), DateTime? lastScrapedAt = default(DateTime?))
        {
            // to ensure "id" is required (not null)
            if (id == null) {
                throw new ArgumentNullException("id is a required property for CreateCompWatchlistResponse and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null) {
                throw new ArgumentNullException("name is a required property for CreateCompWatchlistResponse and cannot be null");
            }
            this.Name = name;
            this.CreatedAt = createdAt;
            // to ensure "userId" is required (not null)
            if (userId == null) {
                throw new ArgumentNullException("userId is a required property for CreateCompWatchlistResponse and cannot be null");
            }
            this.UserId = userId;
            this.Brand = brand;
            this.Condition = condition;
            this.CategoryMain = categoryMain;
            this.Platform = platform;
            this.MinPrice = minPrice;
            this.MaxPrice = maxPrice;
            this.LastMatchedAt = lastMatchedAt;
            this.LastScrapedAt = lastScrapedAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Brand
        /// </summary>
        [DataMember(Name = "brand", EmitDefaultValue = true)]
        public string Brand { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = false)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets Condition
        /// </summary>
        [DataMember(Name = "condition", EmitDefaultValue = true)]
        public string Condition { get; set; }

        /// <summary>
        /// Gets or Sets CategoryMain
        /// </summary>
        [DataMember(Name = "categoryMain", EmitDefaultValue = true)]
        public string CategoryMain { get; set; }

        /// <summary>
        /// Gets or Sets Platform
        /// </summary>
        [DataMember(Name = "platform", EmitDefaultValue = true)]
        public string Platform { get; set; }

        /// <summary>
        /// Gets or Sets MinPrice
        /// </summary>
        [DataMember(Name = "minPrice", EmitDefaultValue = true)]
        public string MinPrice { get; set; }

        /// <summary>
        /// Gets or Sets MaxPrice
        /// </summary>
        [DataMember(Name = "maxPrice", EmitDefaultValue = true)]
        public string MaxPrice { get; set; }

        /// <summary>
        /// Gets or Sets LastMatchedAt
        /// </summary>
        [DataMember(Name = "lastMatchedAt", EmitDefaultValue = true)]
        public DateTime? LastMatchedAt { get; set; }

        /// <summary>
        /// Gets or Sets LastScrapedAt
        /// </summary>
        [DataMember(Name = "lastScrapedAt", EmitDefaultValue = true)]
        public DateTime? LastScrapedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateCompWatchlistResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("  CategoryMain: ").Append(CategoryMain).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  MinPrice: ").Append(MinPrice).Append("\n");
            sb.Append("  MaxPrice: ").Append(MaxPrice).Append("\n");
            sb.Append("  LastMatchedAt: ").Append(LastMatchedAt).Append("\n");
            sb.Append("  LastScrapedAt: ").Append(LastScrapedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateCompWatchlistResponse);
        }

        /// <summary>
        /// Returns true if CreateCompWatchlistResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateCompWatchlistResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCompWatchlistResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Brand == input.Brand ||
                    (this.Brand != null &&
                    this.Brand.Equals(input.Brand))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.Condition == input.Condition ||
                    (this.Condition != null &&
                    this.Condition.Equals(input.Condition))
                ) && 
                (
                    this.CategoryMain == input.CategoryMain ||
                    (this.CategoryMain != null &&
                    this.CategoryMain.Equals(input.CategoryMain))
                ) && 
                (
                    this.Platform == input.Platform ||
                    (this.Platform != null &&
                    this.Platform.Equals(input.Platform))
                ) && 
                (
                    this.MinPrice == input.MinPrice ||
                    (this.MinPrice != null &&
                    this.MinPrice.Equals(input.MinPrice))
                ) && 
                (
                    this.MaxPrice == input.MaxPrice ||
                    (this.MaxPrice != null &&
                    this.MaxPrice.Equals(input.MaxPrice))
                ) && 
                (
                    this.LastMatchedAt == input.LastMatchedAt ||
                    (this.LastMatchedAt != null &&
                    this.LastMatchedAt.Equals(input.LastMatchedAt))
                ) && 
                (
                    this.LastScrapedAt == input.LastScrapedAt ||
                    (this.LastScrapedAt != null &&
                    this.LastScrapedAt.Equals(input.LastScrapedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.Brand != null)
                {
                    hashCode = (hashCode * 59) + this.Brand.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.UserId != null)
                {
                    hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                }
                if (this.Condition != null)
                {
                    hashCode = (hashCode * 59) + this.Condition.GetHashCode();
                }
                if (this.CategoryMain != null)
                {
                    hashCode = (hashCode * 59) + this.CategoryMain.GetHashCode();
                }
                if (this.Platform != null)
                {
                    hashCode = (hashCode * 59) + this.Platform.GetHashCode();
                }
                if (this.MinPrice != null)
                {
                    hashCode = (hashCode * 59) + this.MinPrice.GetHashCode();
                }
                if (this.MaxPrice != null)
                {
                    hashCode = (hashCode * 59) + this.MaxPrice.GetHashCode();
                }
                if (this.LastMatchedAt != null)
                {
                    hashCode = (hashCode * 59) + this.LastMatchedAt.GetHashCode();
                }
                if (this.LastScrapedAt != null)
                {
                    hashCode = (hashCode * 59) + this.LastScrapedAt.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
