/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.Client.OpenAPIDateConverter;

namespace net.crossly.Model
{
    /// <summary>
    /// CreateOrderCancelResponse
    /// </summary>
    [DataContract(Name = "CreateOrderCancelResponse")]
    public partial class CreateOrderCancelResponse : IEquatable<CreateOrderCancelResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOrderCancelResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateOrderCancelResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOrderCancelResponse" /> class.
        /// </summary>
        /// <param name="orderId">orderId (required).</param>
        /// <param name="platform">platform (required).</param>
        /// <param name="cancelledInCrossly">cancelledInCrossly (required).</param>
        /// <param name="platformCancel">platformCancel (required).</param>
        public CreateOrderCancelResponse(string orderId = default(string), string platform = default(string), bool cancelledInCrossly = default(bool), string platformCancel = default(string))
        {
            // to ensure "orderId" is required (not null)
            if (orderId == null) {
                throw new ArgumentNullException("orderId is a required property for CreateOrderCancelResponse and cannot be null");
            }
            this.OrderId = orderId;
            // to ensure "platform" is required (not null)
            if (platform == null) {
                throw new ArgumentNullException("platform is a required property for CreateOrderCancelResponse and cannot be null");
            }
            this.Platform = platform;
            this.CancelledInCrossly = cancelledInCrossly;
            // to ensure "platformCancel" is required (not null)
            if (platformCancel == null) {
                throw new ArgumentNullException("platformCancel is a required property for CreateOrderCancelResponse and cannot be null");
            }
            this.PlatformCancel = platformCancel;
        }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [DataMember(Name = "orderId", IsRequired = true, EmitDefaultValue = false)]
        public string OrderId { get; set; }

        /// <summary>
        /// Gets or Sets Platform
        /// </summary>
        [DataMember(Name = "platform", IsRequired = true, EmitDefaultValue = false)]
        public string Platform { get; set; }

        /// <summary>
        /// Gets or Sets CancelledInCrossly
        /// </summary>
        [DataMember(Name = "cancelledInCrossly", IsRequired = true, EmitDefaultValue = true)]
        public bool CancelledInCrossly { get; set; }

        /// <summary>
        /// Gets or Sets PlatformCancel
        /// </summary>
        [DataMember(Name = "platformCancel", IsRequired = true, EmitDefaultValue = false)]
        public string PlatformCancel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateOrderCancelResponse {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  CancelledInCrossly: ").Append(CancelledInCrossly).Append("\n");
            sb.Append("  PlatformCancel: ").Append(PlatformCancel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateOrderCancelResponse);
        }

        /// <summary>
        /// Returns true if CreateOrderCancelResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateOrderCancelResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateOrderCancelResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.OrderId == input.OrderId ||
                    (this.OrderId != null &&
                    this.OrderId.Equals(input.OrderId))
                ) && 
                (
                    this.Platform == input.Platform ||
                    (this.Platform != null &&
                    this.Platform.Equals(input.Platform))
                ) && 
                (
                    this.CancelledInCrossly == input.CancelledInCrossly ||
                    this.CancelledInCrossly.Equals(input.CancelledInCrossly)
                ) && 
                (
                    this.PlatformCancel == input.PlatformCancel ||
                    (this.PlatformCancel != null &&
                    this.PlatformCancel.Equals(input.PlatformCancel))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OrderId != null)
                {
                    hashCode = (hashCode * 59) + this.OrderId.GetHashCode();
                }
                if (this.Platform != null)
                {
                    hashCode = (hashCode * 59) + this.Platform.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.CancelledInCrossly.GetHashCode();
                if (this.PlatformCancel != null)
                {
                    hashCode = (hashCode * 59) + this.PlatformCancel.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
