/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.Client.OpenAPIDateConverter;

namespace net.crossly.Model
{
    /// <summary>
    /// CreateCbxWalletPaymentQuoteResponse
    /// </summary>
    [DataContract(Name = "CreateCbxWalletPaymentQuoteResponse")]
    public partial class CreateCbxWalletPaymentQuoteResponse : IEquatable<CreateCbxWalletPaymentQuoteResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCbxWalletPaymentQuoteResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateCbxWalletPaymentQuoteResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCbxWalletPaymentQuoteResponse" /> class.
        /// </summary>
        /// <param name="transactionBase64">transactionBase64 (required).</param>
        /// <param name="baseUnits">baseUnits (required).</param>
        /// <param name="valueCents">valueCents (required).</param>
        /// <param name="centsPerToken">centsPerToken (required).</param>
        /// <param name="sourceTokenAccount">sourceTokenAccount (required).</param>
        /// <param name="destinationTokenAccount">destinationTokenAccount (required).</param>
        /// <param name="destinationOwner">destinationOwner (required).</param>
        /// <param name="recentBlockhash">recentBlockhash (required).</param>
        /// <param name="lastValidBlockHeight">lastValidBlockHeight (required).</param>
        public CreateCbxWalletPaymentQuoteResponse(string transactionBase64 = default(string), string baseUnits = default(string), decimal valueCents = default(decimal), decimal centsPerToken = default(decimal), string sourceTokenAccount = default(string), string destinationTokenAccount = default(string), string destinationOwner = default(string), string recentBlockhash = default(string), decimal lastValidBlockHeight = default(decimal))
        {
            // to ensure "transactionBase64" is required (not null)
            if (transactionBase64 == null) {
                throw new ArgumentNullException("transactionBase64 is a required property for CreateCbxWalletPaymentQuoteResponse and cannot be null");
            }
            this.TransactionBase64 = transactionBase64;
            // to ensure "baseUnits" is required (not null)
            if (baseUnits == null) {
                throw new ArgumentNullException("baseUnits is a required property for CreateCbxWalletPaymentQuoteResponse and cannot be null");
            }
            this.BaseUnits = baseUnits;
            this.ValueCents = valueCents;
            this.CentsPerToken = centsPerToken;
            // to ensure "sourceTokenAccount" is required (not null)
            if (sourceTokenAccount == null) {
                throw new ArgumentNullException("sourceTokenAccount is a required property for CreateCbxWalletPaymentQuoteResponse and cannot be null");
            }
            this.SourceTokenAccount = sourceTokenAccount;
            // to ensure "destinationTokenAccount" is required (not null)
            if (destinationTokenAccount == null) {
                throw new ArgumentNullException("destinationTokenAccount is a required property for CreateCbxWalletPaymentQuoteResponse and cannot be null");
            }
            this.DestinationTokenAccount = destinationTokenAccount;
            // to ensure "destinationOwner" is required (not null)
            if (destinationOwner == null) {
                throw new ArgumentNullException("destinationOwner is a required property for CreateCbxWalletPaymentQuoteResponse and cannot be null");
            }
            this.DestinationOwner = destinationOwner;
            // to ensure "recentBlockhash" is required (not null)
            if (recentBlockhash == null) {
                throw new ArgumentNullException("recentBlockhash is a required property for CreateCbxWalletPaymentQuoteResponse and cannot be null");
            }
            this.RecentBlockhash = recentBlockhash;
            this.LastValidBlockHeight = lastValidBlockHeight;
        }

        /// <summary>
        /// Gets or Sets TransactionBase64
        /// </summary>
        [DataMember(Name = "transactionBase64", IsRequired = true, EmitDefaultValue = false)]
        public string TransactionBase64 { get; set; }

        /// <summary>
        /// Gets or Sets BaseUnits
        /// </summary>
        [DataMember(Name = "baseUnits", IsRequired = true, EmitDefaultValue = false)]
        public string BaseUnits { get; set; }

        /// <summary>
        /// Gets or Sets ValueCents
        /// </summary>
        [DataMember(Name = "valueCents", IsRequired = true, EmitDefaultValue = false)]
        public decimal ValueCents { get; set; }

        /// <summary>
        /// Gets or Sets CentsPerToken
        /// </summary>
        [DataMember(Name = "centsPerToken", IsRequired = true, EmitDefaultValue = false)]
        public decimal CentsPerToken { get; set; }

        /// <summary>
        /// Gets or Sets SourceTokenAccount
        /// </summary>
        [DataMember(Name = "sourceTokenAccount", IsRequired = true, EmitDefaultValue = false)]
        public string SourceTokenAccount { get; set; }

        /// <summary>
        /// Gets or Sets DestinationTokenAccount
        /// </summary>
        [DataMember(Name = "destinationTokenAccount", IsRequired = true, EmitDefaultValue = false)]
        public string DestinationTokenAccount { get; set; }

        /// <summary>
        /// Gets or Sets DestinationOwner
        /// </summary>
        [DataMember(Name = "destinationOwner", IsRequired = true, EmitDefaultValue = false)]
        public string DestinationOwner { get; set; }

        /// <summary>
        /// Gets or Sets RecentBlockhash
        /// </summary>
        [DataMember(Name = "recentBlockhash", IsRequired = true, EmitDefaultValue = false)]
        public string RecentBlockhash { get; set; }

        /// <summary>
        /// Gets or Sets LastValidBlockHeight
        /// </summary>
        [DataMember(Name = "lastValidBlockHeight", IsRequired = true, EmitDefaultValue = false)]
        public decimal LastValidBlockHeight { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateCbxWalletPaymentQuoteResponse {\n");
            sb.Append("  TransactionBase64: ").Append(TransactionBase64).Append("\n");
            sb.Append("  BaseUnits: ").Append(BaseUnits).Append("\n");
            sb.Append("  ValueCents: ").Append(ValueCents).Append("\n");
            sb.Append("  CentsPerToken: ").Append(CentsPerToken).Append("\n");
            sb.Append("  SourceTokenAccount: ").Append(SourceTokenAccount).Append("\n");
            sb.Append("  DestinationTokenAccount: ").Append(DestinationTokenAccount).Append("\n");
            sb.Append("  DestinationOwner: ").Append(DestinationOwner).Append("\n");
            sb.Append("  RecentBlockhash: ").Append(RecentBlockhash).Append("\n");
            sb.Append("  LastValidBlockHeight: ").Append(LastValidBlockHeight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateCbxWalletPaymentQuoteResponse);
        }

        /// <summary>
        /// Returns true if CreateCbxWalletPaymentQuoteResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateCbxWalletPaymentQuoteResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCbxWalletPaymentQuoteResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TransactionBase64 == input.TransactionBase64 ||
                    (this.TransactionBase64 != null &&
                    this.TransactionBase64.Equals(input.TransactionBase64))
                ) && 
                (
                    this.BaseUnits == input.BaseUnits ||
                    (this.BaseUnits != null &&
                    this.BaseUnits.Equals(input.BaseUnits))
                ) && 
                (
                    this.ValueCents == input.ValueCents ||
                    this.ValueCents.Equals(input.ValueCents)
                ) && 
                (
                    this.CentsPerToken == input.CentsPerToken ||
                    this.CentsPerToken.Equals(input.CentsPerToken)
                ) && 
                (
                    this.SourceTokenAccount == input.SourceTokenAccount ||
                    (this.SourceTokenAccount != null &&
                    this.SourceTokenAccount.Equals(input.SourceTokenAccount))
                ) && 
                (
                    this.DestinationTokenAccount == input.DestinationTokenAccount ||
                    (this.DestinationTokenAccount != null &&
                    this.DestinationTokenAccount.Equals(input.DestinationTokenAccount))
                ) && 
                (
                    this.DestinationOwner == input.DestinationOwner ||
                    (this.DestinationOwner != null &&
                    this.DestinationOwner.Equals(input.DestinationOwner))
                ) && 
                (
                    this.RecentBlockhash == input.RecentBlockhash ||
                    (this.RecentBlockhash != null &&
                    this.RecentBlockhash.Equals(input.RecentBlockhash))
                ) && 
                (
                    this.LastValidBlockHeight == input.LastValidBlockHeight ||
                    this.LastValidBlockHeight.Equals(input.LastValidBlockHeight)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TransactionBase64 != null)
                {
                    hashCode = (hashCode * 59) + this.TransactionBase64.GetHashCode();
                }
                if (this.BaseUnits != null)
                {
                    hashCode = (hashCode * 59) + this.BaseUnits.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ValueCents.GetHashCode();
                hashCode = (hashCode * 59) + this.CentsPerToken.GetHashCode();
                if (this.SourceTokenAccount != null)
                {
                    hashCode = (hashCode * 59) + this.SourceTokenAccount.GetHashCode();
                }
                if (this.DestinationTokenAccount != null)
                {
                    hashCode = (hashCode * 59) + this.DestinationTokenAccount.GetHashCode();
                }
                if (this.DestinationOwner != null)
                {
                    hashCode = (hashCode * 59) + this.DestinationOwner.GetHashCode();
                }
                if (this.RecentBlockhash != null)
                {
                    hashCode = (hashCode * 59) + this.RecentBlockhash.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.LastValidBlockHeight.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
