/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.Client.OpenAPIDateConverter;

namespace net.crossly.Model
{
    /// <summary>
    /// CreateAdOffsiteResumeResponse
    /// </summary>
    [DataContract(Name = "CreateAdOffsiteResumeResponse")]
    public partial class CreateAdOffsiteResumeResponse : IEquatable<CreateAdOffsiteResumeResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAdOffsiteResumeResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateAdOffsiteResumeResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAdOffsiteResumeResponse" /> class.
        /// </summary>
        /// <param name="cleared">cleared (required).</param>
        public CreateAdOffsiteResumeResponse(bool cleared = default(bool))
        {
            this.Cleared = cleared;
        }

        /// <summary>
        /// Gets or Sets Cleared
        /// </summary>
        [DataMember(Name = "cleared", IsRequired = true, EmitDefaultValue = true)]
        public bool Cleared { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateAdOffsiteResumeResponse {\n");
            sb.Append("  Cleared: ").Append(Cleared).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateAdOffsiteResumeResponse);
        }

        /// <summary>
        /// Returns true if CreateAdOffsiteResumeResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateAdOffsiteResumeResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateAdOffsiteResumeResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Cleared == input.Cleared ||
                    this.Cleared.Equals(input.Cleared)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Cleared.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
