/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.Client.OpenAPIDateConverter;

namespace net.crossly.Model
{
    /// <summary>
    /// CreateBuyerOfferResponseDataOffer
    /// </summary>
    [DataContract(Name = "CreateBuyerOfferResponse_data_offer")]
    public partial class CreateBuyerOfferResponseDataOffer : IEquatable<CreateBuyerOfferResponseDataOffer>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateBuyerOfferResponseDataOffer" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateBuyerOfferResponseDataOffer() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateBuyerOfferResponseDataOffer" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="platformListingId">platformListingId (required).</param>
        /// <param name="buyerUserId">buyerUserId (required).</param>
        /// <param name="amountCents">amountCents (required).</param>
        /// <param name="message">message.</param>
        public CreateBuyerOfferResponseDataOffer(string id = default(string), string status = default(string), string platformListingId = default(string), string buyerUserId = default(string), decimal amountCents = default(decimal), string message = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null) {
                throw new ArgumentNullException("id is a required property for CreateBuyerOfferResponseDataOffer and cannot be null");
            }
            this.Id = id;
            // to ensure "status" is required (not null)
            if (status == null) {
                throw new ArgumentNullException("status is a required property for CreateBuyerOfferResponseDataOffer and cannot be null");
            }
            this.Status = status;
            // to ensure "platformListingId" is required (not null)
            if (platformListingId == null) {
                throw new ArgumentNullException("platformListingId is a required property for CreateBuyerOfferResponseDataOffer and cannot be null");
            }
            this.PlatformListingId = platformListingId;
            // to ensure "buyerUserId" is required (not null)
            if (buyerUserId == null) {
                throw new ArgumentNullException("buyerUserId is a required property for CreateBuyerOfferResponseDataOffer and cannot be null");
            }
            this.BuyerUserId = buyerUserId;
            this.AmountCents = amountCents;
            this.Message = message;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets PlatformListingId
        /// </summary>
        [DataMember(Name = "platformListingId", IsRequired = true, EmitDefaultValue = false)]
        public string PlatformListingId { get; set; }

        /// <summary>
        /// Gets or Sets BuyerUserId
        /// </summary>
        [DataMember(Name = "buyerUserId", IsRequired = true, EmitDefaultValue = false)]
        public string BuyerUserId { get; set; }

        /// <summary>
        /// Gets or Sets AmountCents
        /// </summary>
        [DataMember(Name = "amountCents", IsRequired = true, EmitDefaultValue = false)]
        public decimal AmountCents { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateBuyerOfferResponseDataOffer {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  PlatformListingId: ").Append(PlatformListingId).Append("\n");
            sb.Append("  BuyerUserId: ").Append(BuyerUserId).Append("\n");
            sb.Append("  AmountCents: ").Append(AmountCents).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateBuyerOfferResponseDataOffer);
        }

        /// <summary>
        /// Returns true if CreateBuyerOfferResponseDataOffer instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateBuyerOfferResponseDataOffer to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateBuyerOfferResponseDataOffer input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.PlatformListingId == input.PlatformListingId ||
                    (this.PlatformListingId != null &&
                    this.PlatformListingId.Equals(input.PlatformListingId))
                ) && 
                (
                    this.BuyerUserId == input.BuyerUserId ||
                    (this.BuyerUserId != null &&
                    this.BuyerUserId.Equals(input.BuyerUserId))
                ) && 
                (
                    this.AmountCents == input.AmountCents ||
                    this.AmountCents.Equals(input.AmountCents)
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                if (this.PlatformListingId != null)
                {
                    hashCode = (hashCode * 59) + this.PlatformListingId.GetHashCode();
                }
                if (this.BuyerUserId != null)
                {
                    hashCode = (hashCode * 59) + this.BuyerUserId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.AmountCents.GetHashCode();
                if (this.Message != null)
                {
                    hashCode = (hashCode * 59) + this.Message.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
