/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.Client.OpenAPIDateConverter;

namespace net.crossly.Model
{
    /// <summary>
    /// GetActionLogFacetResponse
    /// </summary>
    [DataContract(Name = "GetActionLogFacetResponse")]
    public partial class GetActionLogFacetResponse : IEquatable<GetActionLogFacetResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetActionLogFacetResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetActionLogFacetResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetActionLogFacetResponse" /> class.
        /// </summary>
        /// <param name="platforms">platforms (required).</param>
        /// <param name="actions">actions (required).</param>
        /// <param name="categories">categories (required).</param>
        public GetActionLogFacetResponse(List<string> platforms = default(List<string>), List<string> actions = default(List<string>), List<string> categories = default(List<string>))
        {
            // to ensure "platforms" is required (not null)
            if (platforms == null) {
                throw new ArgumentNullException("platforms is a required property for GetActionLogFacetResponse and cannot be null");
            }
            this.Platforms = platforms;
            // to ensure "actions" is required (not null)
            if (actions == null) {
                throw new ArgumentNullException("actions is a required property for GetActionLogFacetResponse and cannot be null");
            }
            this.Actions = actions;
            // to ensure "categories" is required (not null)
            if (categories == null) {
                throw new ArgumentNullException("categories is a required property for GetActionLogFacetResponse and cannot be null");
            }
            this.Categories = categories;
        }

        /// <summary>
        /// Gets or Sets Platforms
        /// </summary>
        [DataMember(Name = "platforms", IsRequired = true, EmitDefaultValue = false)]
        public List<string> Platforms { get; set; }

        /// <summary>
        /// Gets or Sets Actions
        /// </summary>
        [DataMember(Name = "actions", IsRequired = true, EmitDefaultValue = false)]
        public List<string> Actions { get; set; }

        /// <summary>
        /// Gets or Sets Categories
        /// </summary>
        [DataMember(Name = "categories", IsRequired = true, EmitDefaultValue = false)]
        public List<string> Categories { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetActionLogFacetResponse {\n");
            sb.Append("  Platforms: ").Append(Platforms).Append("\n");
            sb.Append("  Actions: ").Append(Actions).Append("\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetActionLogFacetResponse);
        }

        /// <summary>
        /// Returns true if GetActionLogFacetResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetActionLogFacetResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetActionLogFacetResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Platforms == input.Platforms ||
                    this.Platforms != null &&
                    input.Platforms != null &&
                    this.Platforms.SequenceEqual(input.Platforms)
                ) && 
                (
                    this.Actions == input.Actions ||
                    this.Actions != null &&
                    input.Actions != null &&
                    this.Actions.SequenceEqual(input.Actions)
                ) && 
                (
                    this.Categories == input.Categories ||
                    this.Categories != null &&
                    input.Categories != null &&
                    this.Categories.SequenceEqual(input.Categories)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Platforms != null)
                {
                    hashCode = (hashCode * 59) + this.Platforms.GetHashCode();
                }
                if (this.Actions != null)
                {
                    hashCode = (hashCode * 59) + this.Actions.GetHashCode();
                }
                if (this.Categories != null)
                {
                    hashCode = (hashCode * 59) + this.Categories.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
