/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.Client.OpenAPIDateConverter;

namespace net.crossly.Model
{
    /// <summary>
    /// GetBuyerCatalogListingResponse
    /// </summary>
    [DataContract(Name = "GetBuyerCatalogListingResponse")]
    public partial class GetBuyerCatalogListingResponse : IEquatable<GetBuyerCatalogListingResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetBuyerCatalogListingResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetBuyerCatalogListingResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetBuyerCatalogListingResponse" /> class.
        /// </summary>
        /// <param name="slug">slug (required).</param>
        /// <param name="title">title (required).</param>
        /// <param name="description">description.</param>
        /// <param name="priceCents">priceCents (required).</param>
        /// <param name="compareAtCents">compareAtCents.</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="available">available (required).</param>
        /// <param name="quantityAvailable">quantityAvailable (required).</param>
        /// <param name="condition">condition.</param>
        /// <param name="brand">brand.</param>
        /// <param name="size">size.</param>
        /// <param name="color">color.</param>
        /// <param name="categoryMain">categoryMain.</param>
        /// <param name="categorySub">categorySub.</param>
        /// <param name="images">images (required).</param>
        /// <param name="sellerUsername">sellerUsername.</param>
        /// <param name="sellerDisplayName">sellerDisplayName.</param>
        /// <param name="listedAt">listedAt.</param>
        public GetBuyerCatalogListingResponse(string slug = default(string), string title = default(string), string description = default(string), decimal priceCents = default(decimal), decimal? compareAtCents = default(decimal?), string currency = default(string), string status = default(string), bool available = default(bool), decimal quantityAvailable = default(decimal), string condition = default(string), string brand = default(string), string size = default(string), List<string> color = default(List<string>), string categoryMain = default(string), string categorySub = default(string), List<string> images = default(List<string>), string sellerUsername = default(string), string sellerDisplayName = default(string), string listedAt = default(string))
        {
            // to ensure "slug" is required (not null)
            if (slug == null) {
                throw new ArgumentNullException("slug is a required property for GetBuyerCatalogListingResponse and cannot be null");
            }
            this.Slug = slug;
            // to ensure "title" is required (not null)
            if (title == null) {
                throw new ArgumentNullException("title is a required property for GetBuyerCatalogListingResponse and cannot be null");
            }
            this.Title = title;
            this.PriceCents = priceCents;
            // to ensure "currency" is required (not null)
            if (currency == null) {
                throw new ArgumentNullException("currency is a required property for GetBuyerCatalogListingResponse and cannot be null");
            }
            this.Currency = currency;
            // to ensure "status" is required (not null)
            if (status == null) {
                throw new ArgumentNullException("status is a required property for GetBuyerCatalogListingResponse and cannot be null");
            }
            this.Status = status;
            this.Available = available;
            this.QuantityAvailable = quantityAvailable;
            // to ensure "images" is required (not null)
            if (images == null) {
                throw new ArgumentNullException("images is a required property for GetBuyerCatalogListingResponse and cannot be null");
            }
            this.Images = images;
            this.Description = description;
            this.CompareAtCents = compareAtCents;
            this.Condition = condition;
            this.Brand = brand;
            this.Size = size;
            this.Color = color;
            this.CategoryMain = categoryMain;
            this.CategorySub = categorySub;
            this.SellerUsername = sellerUsername;
            this.SellerDisplayName = sellerDisplayName;
            this.ListedAt = listedAt;
        }

        /// <summary>
        /// Gets or Sets Slug
        /// </summary>
        [DataMember(Name = "slug", IsRequired = true, EmitDefaultValue = false)]
        public string Slug { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets PriceCents
        /// </summary>
        [DataMember(Name = "priceCents", IsRequired = true, EmitDefaultValue = false)]
        public decimal PriceCents { get; set; }

        /// <summary>
        /// Gets or Sets CompareAtCents
        /// </summary>
        [DataMember(Name = "compareAtCents", EmitDefaultValue = true)]
        public decimal? CompareAtCents { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = false)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Available
        /// </summary>
        [DataMember(Name = "available", IsRequired = true, EmitDefaultValue = true)]
        public bool Available { get; set; }

        /// <summary>
        /// Gets or Sets QuantityAvailable
        /// </summary>
        [DataMember(Name = "quantityAvailable", IsRequired = true, EmitDefaultValue = false)]
        public decimal QuantityAvailable { get; set; }

        /// <summary>
        /// Gets or Sets Condition
        /// </summary>
        [DataMember(Name = "condition", EmitDefaultValue = true)]
        public string Condition { get; set; }

        /// <summary>
        /// Gets or Sets Brand
        /// </summary>
        [DataMember(Name = "brand", EmitDefaultValue = true)]
        public string Brand { get; set; }

        /// <summary>
        /// Gets or Sets Size
        /// </summary>
        [DataMember(Name = "size", EmitDefaultValue = true)]
        public string Size { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [DataMember(Name = "color", EmitDefaultValue = true)]
        public List<string> Color { get; set; }

        /// <summary>
        /// Gets or Sets CategoryMain
        /// </summary>
        [DataMember(Name = "categoryMain", EmitDefaultValue = true)]
        public string CategoryMain { get; set; }

        /// <summary>
        /// Gets or Sets CategorySub
        /// </summary>
        [DataMember(Name = "categorySub", EmitDefaultValue = true)]
        public string CategorySub { get; set; }

        /// <summary>
        /// Gets or Sets Images
        /// </summary>
        [DataMember(Name = "images", IsRequired = true, EmitDefaultValue = false)]
        public List<string> Images { get; set; }

        /// <summary>
        /// Gets or Sets SellerUsername
        /// </summary>
        [DataMember(Name = "sellerUsername", EmitDefaultValue = true)]
        public string SellerUsername { get; set; }

        /// <summary>
        /// Gets or Sets SellerDisplayName
        /// </summary>
        [DataMember(Name = "sellerDisplayName", EmitDefaultValue = true)]
        public string SellerDisplayName { get; set; }

        /// <summary>
        /// Gets or Sets ListedAt
        /// </summary>
        [DataMember(Name = "listedAt", EmitDefaultValue = true)]
        public string ListedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetBuyerCatalogListingResponse {\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  PriceCents: ").Append(PriceCents).Append("\n");
            sb.Append("  CompareAtCents: ").Append(CompareAtCents).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Available: ").Append(Available).Append("\n");
            sb.Append("  QuantityAvailable: ").Append(QuantityAvailable).Append("\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  CategoryMain: ").Append(CategoryMain).Append("\n");
            sb.Append("  CategorySub: ").Append(CategorySub).Append("\n");
            sb.Append("  Images: ").Append(Images).Append("\n");
            sb.Append("  SellerUsername: ").Append(SellerUsername).Append("\n");
            sb.Append("  SellerDisplayName: ").Append(SellerDisplayName).Append("\n");
            sb.Append("  ListedAt: ").Append(ListedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetBuyerCatalogListingResponse);
        }

        /// <summary>
        /// Returns true if GetBuyerCatalogListingResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetBuyerCatalogListingResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetBuyerCatalogListingResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Slug == input.Slug ||
                    (this.Slug != null &&
                    this.Slug.Equals(input.Slug))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.PriceCents == input.PriceCents ||
                    this.PriceCents.Equals(input.PriceCents)
                ) && 
                (
                    this.CompareAtCents == input.CompareAtCents ||
                    (this.CompareAtCents != null &&
                    this.CompareAtCents.Equals(input.CompareAtCents))
                ) && 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Available == input.Available ||
                    this.Available.Equals(input.Available)
                ) && 
                (
                    this.QuantityAvailable == input.QuantityAvailable ||
                    this.QuantityAvailable.Equals(input.QuantityAvailable)
                ) && 
                (
                    this.Condition == input.Condition ||
                    (this.Condition != null &&
                    this.Condition.Equals(input.Condition))
                ) && 
                (
                    this.Brand == input.Brand ||
                    (this.Brand != null &&
                    this.Brand.Equals(input.Brand))
                ) && 
                (
                    this.Size == input.Size ||
                    (this.Size != null &&
                    this.Size.Equals(input.Size))
                ) && 
                (
                    this.Color == input.Color ||
                    this.Color != null &&
                    input.Color != null &&
                    this.Color.SequenceEqual(input.Color)
                ) && 
                (
                    this.CategoryMain == input.CategoryMain ||
                    (this.CategoryMain != null &&
                    this.CategoryMain.Equals(input.CategoryMain))
                ) && 
                (
                    this.CategorySub == input.CategorySub ||
                    (this.CategorySub != null &&
                    this.CategorySub.Equals(input.CategorySub))
                ) && 
                (
                    this.Images == input.Images ||
                    this.Images != null &&
                    input.Images != null &&
                    this.Images.SequenceEqual(input.Images)
                ) && 
                (
                    this.SellerUsername == input.SellerUsername ||
                    (this.SellerUsername != null &&
                    this.SellerUsername.Equals(input.SellerUsername))
                ) && 
                (
                    this.SellerDisplayName == input.SellerDisplayName ||
                    (this.SellerDisplayName != null &&
                    this.SellerDisplayName.Equals(input.SellerDisplayName))
                ) && 
                (
                    this.ListedAt == input.ListedAt ||
                    (this.ListedAt != null &&
                    this.ListedAt.Equals(input.ListedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Slug != null)
                {
                    hashCode = (hashCode * 59) + this.Slug.GetHashCode();
                }
                if (this.Title != null)
                {
                    hashCode = (hashCode * 59) + this.Title.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.PriceCents.GetHashCode();
                if (this.CompareAtCents != null)
                {
                    hashCode = (hashCode * 59) + this.CompareAtCents.GetHashCode();
                }
                if (this.Currency != null)
                {
                    hashCode = (hashCode * 59) + this.Currency.GetHashCode();
                }
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Available.GetHashCode();
                hashCode = (hashCode * 59) + this.QuantityAvailable.GetHashCode();
                if (this.Condition != null)
                {
                    hashCode = (hashCode * 59) + this.Condition.GetHashCode();
                }
                if (this.Brand != null)
                {
                    hashCode = (hashCode * 59) + this.Brand.GetHashCode();
                }
                if (this.Size != null)
                {
                    hashCode = (hashCode * 59) + this.Size.GetHashCode();
                }
                if (this.Color != null)
                {
                    hashCode = (hashCode * 59) + this.Color.GetHashCode();
                }
                if (this.CategoryMain != null)
                {
                    hashCode = (hashCode * 59) + this.CategoryMain.GetHashCode();
                }
                if (this.CategorySub != null)
                {
                    hashCode = (hashCode * 59) + this.CategorySub.GetHashCode();
                }
                if (this.Images != null)
                {
                    hashCode = (hashCode * 59) + this.Images.GetHashCode();
                }
                if (this.SellerUsername != null)
                {
                    hashCode = (hashCode * 59) + this.SellerUsername.GetHashCode();
                }
                if (this.SellerDisplayName != null)
                {
                    hashCode = (hashCode * 59) + this.SellerDisplayName.GetHashCode();
                }
                if (this.ListedAt != null)
                {
                    hashCode = (hashCode * 59) + this.ListedAt.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
