/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.Client.OpenAPIDateConverter;

namespace net.crossly.Model
{
    /// <summary>
    /// GetBuyerCatalogListingAvailabilityResponse
    /// </summary>
    [DataContract(Name = "GetBuyerCatalogListingAvailabilityResponse")]
    public partial class GetBuyerCatalogListingAvailabilityResponse : IEquatable<GetBuyerCatalogListingAvailabilityResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetBuyerCatalogListingAvailabilityResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetBuyerCatalogListingAvailabilityResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetBuyerCatalogListingAvailabilityResponse" /> class.
        /// </summary>
        /// <param name="slug">slug (required).</param>
        /// <param name="available">available (required).</param>
        /// <param name="quantityAvailable">quantityAvailable (required).</param>
        /// <param name="priceCents">priceCents (required).</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="status">status (required).</param>
        public GetBuyerCatalogListingAvailabilityResponse(string slug = default(string), bool available = default(bool), decimal quantityAvailable = default(decimal), decimal priceCents = default(decimal), string currency = default(string), string status = default(string))
        {
            // to ensure "slug" is required (not null)
            if (slug == null) {
                throw new ArgumentNullException("slug is a required property for GetBuyerCatalogListingAvailabilityResponse and cannot be null");
            }
            this.Slug = slug;
            this.Available = available;
            this.QuantityAvailable = quantityAvailable;
            this.PriceCents = priceCents;
            // to ensure "currency" is required (not null)
            if (currency == null) {
                throw new ArgumentNullException("currency is a required property for GetBuyerCatalogListingAvailabilityResponse and cannot be null");
            }
            this.Currency = currency;
            // to ensure "status" is required (not null)
            if (status == null) {
                throw new ArgumentNullException("status is a required property for GetBuyerCatalogListingAvailabilityResponse and cannot be null");
            }
            this.Status = status;
        }

        /// <summary>
        /// Gets or Sets Slug
        /// </summary>
        [DataMember(Name = "slug", IsRequired = true, EmitDefaultValue = false)]
        public string Slug { get; set; }

        /// <summary>
        /// Gets or Sets Available
        /// </summary>
        [DataMember(Name = "available", IsRequired = true, EmitDefaultValue = true)]
        public bool Available { get; set; }

        /// <summary>
        /// Gets or Sets QuantityAvailable
        /// </summary>
        [DataMember(Name = "quantityAvailable", IsRequired = true, EmitDefaultValue = false)]
        public decimal QuantityAvailable { get; set; }

        /// <summary>
        /// Gets or Sets PriceCents
        /// </summary>
        [DataMember(Name = "priceCents", IsRequired = true, EmitDefaultValue = false)]
        public decimal PriceCents { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = false)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetBuyerCatalogListingAvailabilityResponse {\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  Available: ").Append(Available).Append("\n");
            sb.Append("  QuantityAvailable: ").Append(QuantityAvailable).Append("\n");
            sb.Append("  PriceCents: ").Append(PriceCents).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetBuyerCatalogListingAvailabilityResponse);
        }

        /// <summary>
        /// Returns true if GetBuyerCatalogListingAvailabilityResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetBuyerCatalogListingAvailabilityResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetBuyerCatalogListingAvailabilityResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Slug == input.Slug ||
                    (this.Slug != null &&
                    this.Slug.Equals(input.Slug))
                ) && 
                (
                    this.Available == input.Available ||
                    this.Available.Equals(input.Available)
                ) && 
                (
                    this.QuantityAvailable == input.QuantityAvailable ||
                    this.QuantityAvailable.Equals(input.QuantityAvailable)
                ) && 
                (
                    this.PriceCents == input.PriceCents ||
                    this.PriceCents.Equals(input.PriceCents)
                ) && 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Slug != null)
                {
                    hashCode = (hashCode * 59) + this.Slug.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Available.GetHashCode();
                hashCode = (hashCode * 59) + this.QuantityAvailable.GetHashCode();
                hashCode = (hashCode * 59) + this.PriceCents.GetHashCode();
                if (this.Currency != null)
                {
                    hashCode = (hashCode * 59) + this.Currency.GetHashCode();
                }
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
