/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.Client.OpenAPIDateConverter;

namespace net.crossly.Model
{
    /// <summary>
    /// GetMagicDraftResponse
    /// </summary>
    [DataContract(Name = "GetMagicDraftResponse")]
    public partial class GetMagicDraftResponse : IEquatable<GetMagicDraftResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMagicDraftResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMagicDraftResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMagicDraftResponse" /> class.
        /// </summary>
        /// <param name="draft">draft (required).</param>
        public GetMagicDraftResponse(GetMagicDraftResponseDraft draft = default(GetMagicDraftResponseDraft))
        {
            // to ensure "draft" is required (not null)
            if (draft == null) {
                throw new ArgumentNullException("draft is a required property for GetMagicDraftResponse and cannot be null");
            }
            this.Draft = draft;
        }

        /// <summary>
        /// Gets or Sets Draft
        /// </summary>
        [DataMember(Name = "draft", IsRequired = true, EmitDefaultValue = false)]
        public GetMagicDraftResponseDraft Draft { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMagicDraftResponse {\n");
            sb.Append("  Draft: ").Append(Draft).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetMagicDraftResponse);
        }

        /// <summary>
        /// Returns true if GetMagicDraftResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetMagicDraftResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetMagicDraftResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Draft == input.Draft ||
                    (this.Draft != null &&
                    this.Draft.Equals(input.Draft))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Draft != null)
                {
                    hashCode = (hashCode * 59) + this.Draft.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
