/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.Client.OpenAPIDateConverter;

namespace net.crossly.Model
{
    /// <summary>
    /// GetMagicDraftResponseDraft
    /// </summary>
    [DataContract(Name = "GetMagicDraftResponse_draft")]
    public partial class GetMagicDraftResponseDraft : IEquatable<GetMagicDraftResponseDraft>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMagicDraftResponseDraft" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMagicDraftResponseDraft() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMagicDraftResponseDraft" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="userId">userId (required).</param>
        /// <param name="listingId">listingId.</param>
        /// <param name="runId">runId (required).</param>
        /// <param name="selectedMatchKeys">selectedMatchKeys.</param>
        /// <param name="chosenPriceCents">chosenPriceCents.</param>
        /// <param name="chosenQuantity">chosenQuantity.</param>
        /// <param name="chosenCondition">chosenCondition.</param>
        public GetMagicDraftResponseDraft(string id = default(string), DateTime createdAt = default(DateTime), string userId = default(string), string listingId = default(string), string runId = default(string), List<string> selectedMatchKeys = default(List<string>), decimal? chosenPriceCents = default(decimal?), decimal? chosenQuantity = default(decimal?), string chosenCondition = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null) {
                throw new ArgumentNullException("id is a required property for GetMagicDraftResponseDraft and cannot be null");
            }
            this.Id = id;
            this.CreatedAt = createdAt;
            // to ensure "userId" is required (not null)
            if (userId == null) {
                throw new ArgumentNullException("userId is a required property for GetMagicDraftResponseDraft and cannot be null");
            }
            this.UserId = userId;
            // to ensure "runId" is required (not null)
            if (runId == null) {
                throw new ArgumentNullException("runId is a required property for GetMagicDraftResponseDraft and cannot be null");
            }
            this.RunId = runId;
            this.ListingId = listingId;
            this.SelectedMatchKeys = selectedMatchKeys;
            this.ChosenPriceCents = chosenPriceCents;
            this.ChosenQuantity = chosenQuantity;
            this.ChosenCondition = chosenCondition;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = false)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets ListingId
        /// </summary>
        [DataMember(Name = "listingId", EmitDefaultValue = true)]
        public string ListingId { get; set; }

        /// <summary>
        /// Gets or Sets RunId
        /// </summary>
        [DataMember(Name = "runId", IsRequired = true, EmitDefaultValue = false)]
        public string RunId { get; set; }

        /// <summary>
        /// Gets or Sets SelectedMatchKeys
        /// </summary>
        [DataMember(Name = "selectedMatchKeys", EmitDefaultValue = true)]
        public List<string> SelectedMatchKeys { get; set; }

        /// <summary>
        /// Gets or Sets ChosenPriceCents
        /// </summary>
        [DataMember(Name = "chosenPriceCents", EmitDefaultValue = true)]
        public decimal? ChosenPriceCents { get; set; }

        /// <summary>
        /// Gets or Sets ChosenQuantity
        /// </summary>
        [DataMember(Name = "chosenQuantity", EmitDefaultValue = true)]
        public decimal? ChosenQuantity { get; set; }

        /// <summary>
        /// Gets or Sets ChosenCondition
        /// </summary>
        [DataMember(Name = "chosenCondition", EmitDefaultValue = true)]
        public string ChosenCondition { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMagicDraftResponseDraft {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  ListingId: ").Append(ListingId).Append("\n");
            sb.Append("  RunId: ").Append(RunId).Append("\n");
            sb.Append("  SelectedMatchKeys: ").Append(SelectedMatchKeys).Append("\n");
            sb.Append("  ChosenPriceCents: ").Append(ChosenPriceCents).Append("\n");
            sb.Append("  ChosenQuantity: ").Append(ChosenQuantity).Append("\n");
            sb.Append("  ChosenCondition: ").Append(ChosenCondition).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetMagicDraftResponseDraft);
        }

        /// <summary>
        /// Returns true if GetMagicDraftResponseDraft instances are equal
        /// </summary>
        /// <param name="input">Instance of GetMagicDraftResponseDraft to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetMagicDraftResponseDraft input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.ListingId == input.ListingId ||
                    (this.ListingId != null &&
                    this.ListingId.Equals(input.ListingId))
                ) && 
                (
                    this.RunId == input.RunId ||
                    (this.RunId != null &&
                    this.RunId.Equals(input.RunId))
                ) && 
                (
                    this.SelectedMatchKeys == input.SelectedMatchKeys ||
                    this.SelectedMatchKeys != null &&
                    input.SelectedMatchKeys != null &&
                    this.SelectedMatchKeys.SequenceEqual(input.SelectedMatchKeys)
                ) && 
                (
                    this.ChosenPriceCents == input.ChosenPriceCents ||
                    (this.ChosenPriceCents != null &&
                    this.ChosenPriceCents.Equals(input.ChosenPriceCents))
                ) && 
                (
                    this.ChosenQuantity == input.ChosenQuantity ||
                    (this.ChosenQuantity != null &&
                    this.ChosenQuantity.Equals(input.ChosenQuantity))
                ) && 
                (
                    this.ChosenCondition == input.ChosenCondition ||
                    (this.ChosenCondition != null &&
                    this.ChosenCondition.Equals(input.ChosenCondition))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.UserId != null)
                {
                    hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                }
                if (this.ListingId != null)
                {
                    hashCode = (hashCode * 59) + this.ListingId.GetHashCode();
                }
                if (this.RunId != null)
                {
                    hashCode = (hashCode * 59) + this.RunId.GetHashCode();
                }
                if (this.SelectedMatchKeys != null)
                {
                    hashCode = (hashCode * 59) + this.SelectedMatchKeys.GetHashCode();
                }
                if (this.ChosenPriceCents != null)
                {
                    hashCode = (hashCode * 59) + this.ChosenPriceCents.GetHashCode();
                }
                if (this.ChosenQuantity != null)
                {
                    hashCode = (hashCode * 59) + this.ChosenQuantity.GetHashCode();
                }
                if (this.ChosenCondition != null)
                {
                    hashCode = (hashCode * 59) + this.ChosenCondition.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
