/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = net.crossly.Client.OpenAPIDateConverter;

namespace net.crossly.Model
{
    /// <summary>
    /// GetNetworkPoolResponse
    /// </summary>
    [DataContract(Name = "GetNetworkPoolResponse")]
    public partial class GetNetworkPoolResponse : IEquatable<GetNetworkPoolResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNetworkPoolResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetNetworkPoolResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNetworkPoolResponse" /> class.
        /// </summary>
        /// <param name="member">member (required).</param>
        public GetNetworkPoolResponse(GetNetworkPoolResponseMember member = default(GetNetworkPoolResponseMember))
        {
            // to ensure "member" is required (not null)
            if (member == null) {
                throw new ArgumentNullException("member is a required property for GetNetworkPoolResponse and cannot be null");
            }
            this.Member = member;
        }

        /// <summary>
        /// Gets or Sets Member
        /// </summary>
        [DataMember(Name = "member", IsRequired = true, EmitDefaultValue = false)]
        public GetNetworkPoolResponseMember Member { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNetworkPoolResponse {\n");
            sb.Append("  Member: ").Append(Member).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetNetworkPoolResponse);
        }

        /// <summary>
        /// Returns true if GetNetworkPoolResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetNetworkPoolResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetNetworkPoolResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Member == input.Member ||
                    (this.Member != null &&
                    this.Member.Equals(input.Member))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Member != null)
                {
                    hashCode = (hashCode * 59) + this.Member.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
