/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using net.crossly.Client;
using net.crossly.Api;
// uncomment below to import models
//using net.crossly.Model;

namespace net.crossly.Test.Api
{
    /// <summary>
    ///  Class for testing ConnectionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ConnectionsApiTests : IDisposable
    {
        private ConnectionsApi instance;

        public ConnectionsApiTests()
        {
            instance = new ConnectionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConnectionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ConnectionsApi
            //Assert.IsType<ConnectionsApi>(instance);
        }

        /// <summary>
        /// Test GetConnectionHealth
        /// </summary>
        [Fact]
        public void GetConnectionHealthTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? includeUnconnected = null;
            //var response = instance.GetConnectionHealth(includeUnconnected);
            //Assert.IsType<GetConnectionHealthResponse>(response);
        }

        /// <summary>
        /// Test ListDevices
        /// </summary>
        [Fact]
        public void ListDevicesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListDevices();
            //Assert.IsType<V1List>(response);
        }
    }
}
