/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using net.crossly.Client;
using net.crossly.Api;
// uncomment below to import models
//using net.crossly.Model;

namespace net.crossly.Test.Api
{
    /// <summary>
    ///  Class for testing SalesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SalesApiTests : IDisposable
    {
        private SalesApi instance;

        public SalesApiTests()
        {
            instance = new SalesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SalesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SalesApi
            //Assert.IsType<SalesApi>(instance);
        }

        /// <summary>
        /// Test CreateSaleBulkDelete
        /// </summary>
        [Fact]
        public void CreateSaleBulkDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.CreateSaleBulkDelete();
            //Assert.IsType<CreateSaleBulkDeleteResponse>(response);
        }

        /// <summary>
        /// Test ListSales
        /// </summary>
        [Fact]
        public void ListSalesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListSales();
            //Assert.IsType<V1List>(response);
        }
    }
}
