/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing CreateBuyerActivityResponseMatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateBuyerActivityResponseMatchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateBuyerActivityResponseMatch
        //private CreateBuyerActivityResponseMatch instance;

        public CreateBuyerActivityResponseMatchTests()
        {
            // TODO uncomment below to create an instance of CreateBuyerActivityResponseMatch
            //instance = new CreateBuyerActivityResponseMatch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateBuyerActivityResponseMatch
        /// </summary>
        [Fact]
        public void CreateBuyerActivityResponseMatchInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateBuyerActivityResponseMatch
            //Assert.IsType<CreateBuyerActivityResponseMatch>(instance);
        }


        /// <summary>
        /// Test the property 'Verdict'
        /// </summary>
        [Fact]
        public void VerdictTest()
        {
            // TODO unit test for the property 'Verdict'
        }
        /// <summary>
        /// Test the property 'Offer'
        /// </summary>
        [Fact]
        public void OfferTest()
        {
            // TODO unit test for the property 'Offer'
        }
        /// <summary>
        /// Test the property 'SavingCents'
        /// </summary>
        [Fact]
        public void SavingCentsTest()
        {
            // TODO unit test for the property 'SavingCents'
        }
        /// <summary>
        /// Test the property 'ConditionComparable'
        /// </summary>
        [Fact]
        public void ConditionComparableTest()
        {
            // TODO unit test for the property 'ConditionComparable'
        }
        /// <summary>
        /// Test the property 'ShippingKnown'
        /// </summary>
        [Fact]
        public void ShippingKnownTest()
        {
            // TODO unit test for the property 'ShippingKnown'
        }
        /// <summary>
        /// Test the property 'Catalog'
        /// </summary>
        [Fact]
        public void CatalogTest()
        {
            // TODO unit test for the property 'Catalog'
        }
        /// <summary>
        /// Test the property 'Alternates'
        /// </summary>
        [Fact]
        public void AlternatesTest()
        {
            // TODO unit test for the property 'Alternates'
        }

    }

}
