/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing CreatePlatformAccountDisconnectResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreatePlatformAccountDisconnectResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreatePlatformAccountDisconnectResponse
        //private CreatePlatformAccountDisconnectResponse instance;

        public CreatePlatformAccountDisconnectResponseTests()
        {
            // TODO uncomment below to create an instance of CreatePlatformAccountDisconnectResponse
            //instance = new CreatePlatformAccountDisconnectResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreatePlatformAccountDisconnectResponse
        /// </summary>
        [Fact]
        public void CreatePlatformAccountDisconnectResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreatePlatformAccountDisconnectResponse
            //Assert.IsType<CreatePlatformAccountDisconnectResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Archived'
        /// </summary>
        [Fact]
        public void ArchivedTest()
        {
            // TODO unit test for the property 'Archived'
        }

    }

}
