/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing CreateAiGenerateListingResponsePriceRangeValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateAiGenerateListingResponsePriceRangeValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateAiGenerateListingResponsePriceRangeValue
        //private CreateAiGenerateListingResponsePriceRangeValue instance;

        public CreateAiGenerateListingResponsePriceRangeValueTests()
        {
            // TODO uncomment below to create an instance of CreateAiGenerateListingResponsePriceRangeValue
            //instance = new CreateAiGenerateListingResponsePriceRangeValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateAiGenerateListingResponsePriceRangeValue
        /// </summary>
        [Fact]
        public void CreateAiGenerateListingResponsePriceRangeValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateAiGenerateListingResponsePriceRangeValue
            //Assert.IsType<CreateAiGenerateListingResponsePriceRangeValue>(instance);
        }


        /// <summary>
        /// Test the property 'Low'
        /// </summary>
        [Fact]
        public void LowTest()
        {
            // TODO unit test for the property 'Low'
        }
        /// <summary>
        /// Test the property 'High'
        /// </summary>
        [Fact]
        public void HighTest()
        {
            // TODO unit test for the property 'High'
        }

    }

}
