/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing CreateCbxCampaignPreviewResponseAllocations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCbxCampaignPreviewResponseAllocationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateCbxCampaignPreviewResponseAllocations
        //private CreateCbxCampaignPreviewResponseAllocations instance;

        public CreateCbxCampaignPreviewResponseAllocationsTests()
        {
            // TODO uncomment below to create an instance of CreateCbxCampaignPreviewResponseAllocations
            //instance = new CreateCbxCampaignPreviewResponseAllocations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateCbxCampaignPreviewResponseAllocations
        /// </summary>
        [Fact]
        public void CreateCbxCampaignPreviewResponseAllocationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateCbxCampaignPreviewResponseAllocations
            //Assert.IsType<CreateCbxCampaignPreviewResponseAllocations>(instance);
        }


        /// <summary>
        /// Test the property 'SubjectId'
        /// </summary>
        [Fact]
        public void SubjectIdTest()
        {
            // TODO unit test for the property 'SubjectId'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'BaseUnits'
        /// </summary>
        [Fact]
        public void BaseUnitsTest()
        {
            // TODO unit test for the property 'BaseUnits'
        }

    }

}
