/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing CreateAiHelpResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateAiHelpResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateAiHelpResponse
        //private CreateAiHelpResponse instance;

        public CreateAiHelpResponseTests()
        {
            // TODO uncomment below to create an instance of CreateAiHelpResponse
            //instance = new CreateAiHelpResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateAiHelpResponse
        /// </summary>
        [Fact]
        public void CreateAiHelpResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateAiHelpResponse
            //Assert.IsType<CreateAiHelpResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Answer'
        /// </summary>
        [Fact]
        public void AnswerTest()
        {
            // TODO unit test for the property 'Answer'
        }
        /// <summary>
        /// Test the property 'SourceSlugs'
        /// </summary>
        [Fact]
        public void SourceSlugsTest()
        {
            // TODO unit test for the property 'SourceSlugs'
        }

    }

}
