/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing CreateCbxCreditDrawResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCbxCreditDrawResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateCbxCreditDrawResponse
        //private CreateCbxCreditDrawResponse instance;

        public CreateCbxCreditDrawResponseTests()
        {
            // TODO uncomment below to create an instance of CreateCbxCreditDrawResponse
            //instance = new CreateCbxCreditDrawResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateCbxCreditDrawResponse
        /// </summary>
        [Fact]
        public void CreateCbxCreditDrawResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateCbxCreditDrawResponse
            //Assert.IsType<CreateCbxCreditDrawResponse>(instance);
        }


        /// <summary>
        /// Test the property 'MovementId'
        /// </summary>
        [Fact]
        public void MovementIdTest()
        {
            // TODO unit test for the property 'MovementId'
        }
        /// <summary>
        /// Test the property 'DrawnCents'
        /// </summary>
        [Fact]
        public void DrawnCentsTest()
        {
            // TODO unit test for the property 'DrawnCents'
        }
        /// <summary>
        /// Test the property 'BaseUnitsGranted'
        /// </summary>
        [Fact]
        public void BaseUnitsGrantedTest()
        {
            // TODO unit test for the property 'BaseUnitsGranted'
        }
        /// <summary>
        /// Test the property 'DueAt'
        /// </summary>
        [Fact]
        public void DueAtTest()
        {
            // TODO unit test for the property 'DueAt'
        }
        /// <summary>
        /// Test the property 'Duplicate'
        /// </summary>
        [Fact]
        public void DuplicateTest()
        {
            // TODO unit test for the property 'Duplicate'
        }

    }

}
