/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetAnalyticTodayResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAnalyticTodayResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAnalyticTodayResponse
        //private GetAnalyticTodayResponse instance;

        public GetAnalyticTodayResponseTests()
        {
            // TODO uncomment below to create an instance of GetAnalyticTodayResponse
            //instance = new GetAnalyticTodayResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAnalyticTodayResponse
        /// </summary>
        [Fact]
        public void GetAnalyticTodayResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAnalyticTodayResponse
            //Assert.IsType<GetAnalyticTodayResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Checklist'
        /// </summary>
        [Fact]
        public void ChecklistTest()
        {
            // TODO unit test for the property 'Checklist'
        }
        /// <summary>
        /// Test the property 'Streak'
        /// </summary>
        [Fact]
        public void StreakTest()
        {
            // TODO unit test for the property 'Streak'
        }
        /// <summary>
        /// Test the property 'ActivitySparkline'
        /// </summary>
        [Fact]
        public void ActivitySparklineTest()
        {
            // TODO unit test for the property 'ActivitySparkline'
        }

    }

}
