/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetAutomationRuleExportResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAutomationRuleExportResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAutomationRuleExportResponse
        //private GetAutomationRuleExportResponse instance;

        public GetAutomationRuleExportResponseTests()
        {
            // TODO uncomment below to create an instance of GetAutomationRuleExportResponse
            //instance = new GetAutomationRuleExportResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAutomationRuleExportResponse
        /// </summary>
        [Fact]
        public void GetAutomationRuleExportResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAutomationRuleExportResponse
            //Assert.IsType<GetAutomationRuleExportResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }
        /// <summary>
        /// Test the property 'SchemaVersion'
        /// </summary>
        [Fact]
        public void SchemaVersionTest()
        {
            // TODO unit test for the property 'SchemaVersion'
        }
        /// <summary>
        /// Test the property 'ExportedAt'
        /// </summary>
        [Fact]
        public void ExportedAtTest()
        {
            // TODO unit test for the property 'ExportedAt'
        }
        /// <summary>
        /// Test the property 'Recipes'
        /// </summary>
        [Fact]
        public void RecipesTest()
        {
            // TODO unit test for the property 'Recipes'
        }

    }

}
