/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetAdOffsiteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAdOffsiteResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAdOffsiteResponse
        //private GetAdOffsiteResponse instance;

        public GetAdOffsiteResponseTests()
        {
            // TODO uncomment below to create an instance of GetAdOffsiteResponse
            //instance = new GetAdOffsiteResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAdOffsiteResponse
        /// </summary>
        [Fact]
        public void GetAdOffsiteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAdOffsiteResponse
            //Assert.IsType<GetAdOffsiteResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'MaxOffsiteShareBps'
        /// </summary>
        [Fact]
        public void MaxOffsiteShareBpsTest()
        {
            // TODO unit test for the property 'MaxOffsiteShareBps'
        }
        /// <summary>
        /// Test the property 'MinReturnBps'
        /// </summary>
        [Fact]
        public void MinReturnBpsTest()
        {
            // TODO unit test for the property 'MinReturnBps'
        }
        /// <summary>
        /// Test the property 'ReturnWindowDays'
        /// </summary>
        [Fact]
        public void ReturnWindowDaysTest()
        {
            // TODO unit test for the property 'ReturnWindowDays'
        }
        /// <summary>
        /// Test the property 'AllowedNetworks'
        /// </summary>
        [Fact]
        public void AllowedNetworksTest()
        {
            // TODO unit test for the property 'AllowedNetworks'
        }
        /// <summary>
        /// Test the property 'AutoPausedAt'
        /// </summary>
        [Fact]
        public void AutoPausedAtTest()
        {
            // TODO unit test for the property 'AutoPausedAt'
        }
        /// <summary>
        /// Test the property 'AutoPausedReason'
        /// </summary>
        [Fact]
        public void AutoPausedReasonTest()
        {
            // TODO unit test for the property 'AutoPausedReason'
        }
        /// <summary>
        /// Test the property 'OptedInAt'
        /// </summary>
        [Fact]
        public void OptedInAtTest()
        {
            // TODO unit test for the property 'OptedInAt'
        }
        /// <summary>
        /// Test the property 'Terms'
        /// </summary>
        [Fact]
        public void TermsTest()
        {
            // TODO unit test for the property 'Terms'
        }
        /// <summary>
        /// Test the property 'NetworkWired'
        /// </summary>
        [Fact]
        public void NetworkWiredTest()
        {
            // TODO unit test for the property 'NetworkWired'
        }

    }

}
