/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetAiStatusResponseCustomConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAiStatusResponseCustomConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAiStatusResponseCustomConfig
        //private GetAiStatusResponseCustomConfig instance;

        public GetAiStatusResponseCustomConfigTests()
        {
            // TODO uncomment below to create an instance of GetAiStatusResponseCustomConfig
            //instance = new GetAiStatusResponseCustomConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAiStatusResponseCustomConfig
        /// </summary>
        [Fact]
        public void GetAiStatusResponseCustomConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAiStatusResponseCustomConfig
            //Assert.IsType<GetAiStatusResponseCustomConfig>(instance);
        }


        /// <summary>
        /// Test the property 'BaseUrl'
        /// </summary>
        [Fact]
        public void BaseUrlTest()
        {
            // TODO unit test for the property 'BaseUrl'
        }
        /// <summary>
        /// Test the property 'TextModel'
        /// </summary>
        [Fact]
        public void TextModelTest()
        {
            // TODO unit test for the property 'TextModel'
        }
        /// <summary>
        /// Test the property 'VisionModel'
        /// </summary>
        [Fact]
        public void VisionModelTest()
        {
            // TODO unit test for the property 'VisionModel'
        }
        /// <summary>
        /// Test the property 'SupportsVision'
        /// </summary>
        [Fact]
        public void SupportsVisionTest()
        {
            // TODO unit test for the property 'SupportsVision'
        }
        /// <summary>
        /// Test the property 'SupportsJsonMode'
        /// </summary>
        [Fact]
        public void SupportsJsonModeTest()
        {
            // TODO unit test for the property 'SupportsJsonMode'
        }

    }

}
