/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetAnalyticTimeseryResponseSeries
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAnalyticTimeseryResponseSeriesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAnalyticTimeseryResponseSeries
        //private GetAnalyticTimeseryResponseSeries instance;

        public GetAnalyticTimeseryResponseSeriesTests()
        {
            // TODO uncomment below to create an instance of GetAnalyticTimeseryResponseSeries
            //instance = new GetAnalyticTimeseryResponseSeries();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAnalyticTimeseryResponseSeries
        /// </summary>
        [Fact]
        public void GetAnalyticTimeseryResponseSeriesInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAnalyticTimeseryResponseSeries
            //Assert.IsType<GetAnalyticTimeseryResponseSeries>(instance);
        }


        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Fact]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }
        /// <summary>
        /// Test the property 'Sales'
        /// </summary>
        [Fact]
        public void SalesTest()
        {
            // TODO unit test for the property 'Sales'
        }
        /// <summary>
        /// Test the property 'Revenue'
        /// </summary>
        [Fact]
        public void RevenueTest()
        {
            // TODO unit test for the property 'Revenue'
        }

    }

}
