/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetConnectionHealthResponseExtension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetConnectionHealthResponseExtensionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetConnectionHealthResponseExtension
        //private GetConnectionHealthResponseExtension instance;

        public GetConnectionHealthResponseExtensionTests()
        {
            // TODO uncomment below to create an instance of GetConnectionHealthResponseExtension
            //instance = new GetConnectionHealthResponseExtension();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetConnectionHealthResponseExtension
        /// </summary>
        [Fact]
        public void GetConnectionHealthResponseExtensionInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetConnectionHealthResponseExtension
            //Assert.IsType<GetConnectionHealthResponseExtension>(instance);
        }


        /// <summary>
        /// Test the property 'Online'
        /// </summary>
        [Fact]
        public void OnlineTest()
        {
            // TODO unit test for the property 'Online'
        }
        /// <summary>
        /// Test the property 'LastBrowserPushAt'
        /// </summary>
        [Fact]
        public void LastBrowserPushAtTest()
        {
            // TODO unit test for the property 'LastBrowserPushAt'
        }
        /// <summary>
        /// Test the property 'LastBrowserPushAgo'
        /// </summary>
        [Fact]
        public void LastBrowserPushAgoTest()
        {
            // TODO unit test for the property 'LastBrowserPushAgo'
        }
        /// <summary>
        /// Test the property 'ReportedVersion'
        /// </summary>
        [Fact]
        public void ReportedVersionTest()
        {
            // TODO unit test for the property 'ReportedVersion'
        }

    }

}
