/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetInboxCannedResponsResponseCannedResponses
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetInboxCannedResponsResponseCannedResponsesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetInboxCannedResponsResponseCannedResponses
        //private GetInboxCannedResponsResponseCannedResponses instance;

        public GetInboxCannedResponsResponseCannedResponsesTests()
        {
            // TODO uncomment below to create an instance of GetInboxCannedResponsResponseCannedResponses
            //instance = new GetInboxCannedResponsResponseCannedResponses();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetInboxCannedResponsResponseCannedResponses
        /// </summary>
        [Fact]
        public void GetInboxCannedResponsResponseCannedResponsesInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetInboxCannedResponsResponseCannedResponses
            //Assert.IsType<GetInboxCannedResponsResponseCannedResponses>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Surface'
        /// </summary>
        [Fact]
        public void SurfaceTest()
        {
            // TODO unit test for the property 'Surface'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

    }

}
