/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetListingVariationGroupResponseGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetListingVariationGroupResponseGroupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetListingVariationGroupResponseGroup
        //private GetListingVariationGroupResponseGroup instance;

        public GetListingVariationGroupResponseGroupTests()
        {
            // TODO uncomment below to create an instance of GetListingVariationGroupResponseGroup
            //instance = new GetListingVariationGroupResponseGroup();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetListingVariationGroupResponseGroup
        /// </summary>
        [Fact]
        public void GetListingVariationGroupResponseGroupInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetListingVariationGroupResponseGroup
            //Assert.IsType<GetListingVariationGroupResponseGroup>(instance);
        }


        /// <summary>
        /// Test the property 'GroupListingId'
        /// </summary>
        [Fact]
        public void GroupListingIdTest()
        {
            // TODO unit test for the property 'GroupListingId'
        }
        /// <summary>
        /// Test the property 'AxisValue'
        /// </summary>
        [Fact]
        public void AxisValueTest()
        {
            // TODO unit test for the property 'AxisValue'
        }

    }

}
