/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetMagicDraftResponseDraft
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMagicDraftResponseDraftTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMagicDraftResponseDraft
        //private GetMagicDraftResponseDraft instance;

        public GetMagicDraftResponseDraftTests()
        {
            // TODO uncomment below to create an instance of GetMagicDraftResponseDraft
            //instance = new GetMagicDraftResponseDraft();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMagicDraftResponseDraft
        /// </summary>
        [Fact]
        public void GetMagicDraftResponseDraftInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMagicDraftResponseDraft
            //Assert.IsType<GetMagicDraftResponseDraft>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'ListingId'
        /// </summary>
        [Fact]
        public void ListingIdTest()
        {
            // TODO unit test for the property 'ListingId'
        }
        /// <summary>
        /// Test the property 'RunId'
        /// </summary>
        [Fact]
        public void RunIdTest()
        {
            // TODO unit test for the property 'RunId'
        }
        /// <summary>
        /// Test the property 'SelectedMatchKeys'
        /// </summary>
        [Fact]
        public void SelectedMatchKeysTest()
        {
            // TODO unit test for the property 'SelectedMatchKeys'
        }
        /// <summary>
        /// Test the property 'ChosenPriceCents'
        /// </summary>
        [Fact]
        public void ChosenPriceCentsTest()
        {
            // TODO unit test for the property 'ChosenPriceCents'
        }
        /// <summary>
        /// Test the property 'ChosenQuantity'
        /// </summary>
        [Fact]
        public void ChosenQuantityTest()
        {
            // TODO unit test for the property 'ChosenQuantity'
        }
        /// <summary>
        /// Test the property 'ChosenCondition'
        /// </summary>
        [Fact]
        public void ChosenConditionTest()
        {
            // TODO unit test for the property 'ChosenCondition'
        }

    }

}
