/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetSpatialPublicResponseSolvedDividers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSpatialPublicResponseSolvedDividersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSpatialPublicResponseSolvedDividers
        //private GetSpatialPublicResponseSolvedDividers instance;

        public GetSpatialPublicResponseSolvedDividersTests()
        {
            // TODO uncomment below to create an instance of GetSpatialPublicResponseSolvedDividers
            //instance = new GetSpatialPublicResponseSolvedDividers();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSpatialPublicResponseSolvedDividers
        /// </summary>
        [Fact]
        public void GetSpatialPublicResponseSolvedDividersInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSpatialPublicResponseSolvedDividers
            //Assert.IsType<GetSpatialPublicResponseSolvedDividers>(instance);
        }


        /// <summary>
        /// Test the property 'ContainerKey'
        /// </summary>
        [Fact]
        public void ContainerKeyTest()
        {
            // TODO unit test for the property 'ContainerKey'
        }
        /// <summary>
        /// Test the property 'ContainerIndex'
        /// </summary>
        [Fact]
        public void ContainerIndexTest()
        {
            // TODO unit test for the property 'ContainerIndex'
        }
        /// <summary>
        /// Test the property 'SlotIndex'
        /// </summary>
        [Fact]
        public void SlotIndexTest()
        {
            // TODO unit test for the property 'SlotIndex'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

    }

}
