/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetVariationGroupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetVariationGroupResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetVariationGroupResponse
        //private GetVariationGroupResponse instance;

        public GetVariationGroupResponseTests()
        {
            // TODO uncomment below to create an instance of GetVariationGroupResponse
            //instance = new GetVariationGroupResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetVariationGroupResponse
        /// </summary>
        [Fact]
        public void GetVariationGroupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetVariationGroupResponse
            //Assert.IsType<GetVariationGroupResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Members'
        /// </summary>
        [Fact]
        public void MembersTest()
        {
            // TODO unit test for the property 'Members'
        }
        /// <summary>
        /// Test the property 'Rollup'
        /// </summary>
        [Fact]
        public void RollupTest()
        {
            // TODO unit test for the property 'Rollup'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
