/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing GetWorkflowChainResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWorkflowChainResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWorkflowChainResponse
        //private GetWorkflowChainResponse instance;

        public GetWorkflowChainResponseTests()
        {
            // TODO uncomment below to create an instance of GetWorkflowChainResponse
            //instance = new GetWorkflowChainResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWorkflowChainResponse
        /// </summary>
        [Fact]
        public void GetWorkflowChainResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWorkflowChainResponse
            //Assert.IsType<GetWorkflowChainResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Chain'
        /// </summary>
        [Fact]
        public void ChainTest()
        {
            // TODO unit test for the property 'Chain'
        }
        /// <summary>
        /// Test the property 'Steps'
        /// </summary>
        [Fact]
        public void StepsTest()
        {
            // TODO unit test for the property 'Steps'
        }

    }

}
