/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing ListTaxonomySuggestItemCatalog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListTaxonomySuggestItemCatalogTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListTaxonomySuggestItemCatalog
        //private ListTaxonomySuggestItemCatalog instance;

        public ListTaxonomySuggestItemCatalogTests()
        {
            // TODO uncomment below to create an instance of ListTaxonomySuggestItemCatalog
            //instance = new ListTaxonomySuggestItemCatalog();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListTaxonomySuggestItemCatalog
        /// </summary>
        [Fact]
        public void ListTaxonomySuggestItemCatalogInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListTaxonomySuggestItemCatalog
            //Assert.IsType<ListTaxonomySuggestItemCatalog>(instance);
        }


        /// <summary>
        /// Test the property 'Department'
        /// </summary>
        [Fact]
        public void DepartmentTest()
        {
            // TODO unit test for the property 'Department'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'CategoryFeatures'
        /// </summary>
        [Fact]
        public void CategoryFeaturesTest()
        {
            // TODO unit test for the property 'CategoryFeatures'
        }

    }

}
