/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing ListCbxSubjectLedgerItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListCbxSubjectLedgerItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListCbxSubjectLedgerItem
        //private ListCbxSubjectLedgerItem instance;

        public ListCbxSubjectLedgerItemTests()
        {
            // TODO uncomment below to create an instance of ListCbxSubjectLedgerItem
            //instance = new ListCbxSubjectLedgerItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListCbxSubjectLedgerItem
        /// </summary>
        [Fact]
        public void ListCbxSubjectLedgerItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListCbxSubjectLedgerItem
            //Assert.IsType<ListCbxSubjectLedgerItem>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DeltaBaseUnits'
        /// </summary>
        [Fact]
        public void DeltaBaseUnitsTest()
        {
            // TODO unit test for the property 'DeltaBaseUnits'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Fact]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [Fact]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
