/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing ListOrdersItemTrackingHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListOrdersItemTrackingHistoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListOrdersItemTrackingHistory
        //private ListOrdersItemTrackingHistory instance;

        public ListOrdersItemTrackingHistoryTests()
        {
            // TODO uncomment below to create an instance of ListOrdersItemTrackingHistory
            //instance = new ListOrdersItemTrackingHistory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListOrdersItemTrackingHistory
        /// </summary>
        [Fact]
        public void ListOrdersItemTrackingHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListOrdersItemTrackingHistory
            //Assert.IsType<ListOrdersItemTrackingHistory>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusDetails'
        /// </summary>
        [Fact]
        public void StatusDetailsTest()
        {
            // TODO unit test for the property 'StatusDetails'
        }
        /// <summary>
        /// Test the property 'StatusDate'
        /// </summary>
        [Fact]
        public void StatusDateTest()
        {
            // TODO unit test for the property 'StatusDate'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

    }

}
