/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.crossly.buyer.Api;
using net.crossly.buyer.Model;
using net.crossly.buyer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.crossly.buyer.Test.Model
{
    /// <summary>
    ///  Class for testing ListSalesItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListSalesItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListSalesItem
        //private ListSalesItem instance;

        public ListSalesItemTests()
        {
            // TODO uncomment below to create an instance of ListSalesItem
            //instance = new ListSalesItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListSalesItem
        /// </summary>
        [Fact]
        public void ListSalesItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListSalesItem
            //Assert.IsType<ListSalesItem>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }
        /// <summary>
        /// Test the property 'CancelledAt'
        /// </summary>
        [Fact]
        public void CancelledAtTest()
        {
            // TODO unit test for the property 'CancelledAt'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'ListingId'
        /// </summary>
        [Fact]
        public void ListingIdTest()
        {
            // TODO unit test for the property 'ListingId'
        }
        /// <summary>
        /// Test the property 'InventoryItemId'
        /// </summary>
        [Fact]
        public void InventoryItemIdTest()
        {
            // TODO unit test for the property 'InventoryItemId'
        }
        /// <summary>
        /// Test the property 'PlatformListingId'
        /// </summary>
        [Fact]
        public void PlatformListingIdTest()
        {
            // TODO unit test for the property 'PlatformListingId'
        }
        /// <summary>
        /// Test the property 'PlatformOrderId'
        /// </summary>
        [Fact]
        public void PlatformOrderIdTest()
        {
            // TODO unit test for the property 'PlatformOrderId'
        }
        /// <summary>
        /// Test the property 'CostOfGoods'
        /// </summary>
        [Fact]
        public void CostOfGoodsTest()
        {
            // TODO unit test for the property 'CostOfGoods'
        }
        /// <summary>
        /// Test the property 'DeletedAt'
        /// </summary>
        [Fact]
        public void DeletedAtTest()
        {
            // TODO unit test for the property 'DeletedAt'
        }
        /// <summary>
        /// Test the property 'SalePrice'
        /// </summary>
        [Fact]
        public void SalePriceTest()
        {
            // TODO unit test for the property 'SalePrice'
        }
        /// <summary>
        /// Test the property 'PlatformFee'
        /// </summary>
        [Fact]
        public void PlatformFeeTest()
        {
            // TODO unit test for the property 'PlatformFee'
        }
        /// <summary>
        /// Test the property 'ShippingCost'
        /// </summary>
        [Fact]
        public void ShippingCostTest()
        {
            // TODO unit test for the property 'ShippingCost'
        }
        /// <summary>
        /// Test the property 'NetProfit'
        /// </summary>
        [Fact]
        public void NetProfitTest()
        {
            // TODO unit test for the property 'NetProfit'
        }
        /// <summary>
        /// Test the property 'TaxCollected'
        /// </summary>
        [Fact]
        public void TaxCollectedTest()
        {
            // TODO unit test for the property 'TaxCollected'
        }
        /// <summary>
        /// Test the property 'ShippingCharged'
        /// </summary>
        [Fact]
        public void ShippingChargedTest()
        {
            // TODO unit test for the property 'ShippingCharged'
        }
        /// <summary>
        /// Test the property 'FeeSource'
        /// </summary>
        [Fact]
        public void FeeSourceTest()
        {
            // TODO unit test for the property 'FeeSource'
        }
        /// <summary>
        /// Test the property 'DetectedBy'
        /// </summary>
        [Fact]
        public void DetectedByTest()
        {
            // TODO unit test for the property 'DetectedBy'
        }
        /// <summary>
        /// Test the property 'DetectedAt'
        /// </summary>
        [Fact]
        public void DetectedAtTest()
        {
            // TODO unit test for the property 'DetectedAt'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Fact]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'RefundedAmount'
        /// </summary>
        [Fact]
        public void RefundedAmountTest()
        {
            // TODO unit test for the property 'RefundedAmount'
        }

    }

}
